Photon-Health/client

packages/elements/src/photon-multirx-form-wrapper/index.tsx

if you select a patient in create new prescription, then close, then create a new patient the form is now empty
task ref https://www.notion.so/photons/Adding-a-new-patient-loads-form-with-previous-state-79d3333a4b67428ba2faf3299c131f29?pvs=4

clear selected patient

---

apps/app/src/views/routes/PatientForm.tsx
apps/app/src/views/routes/UpdatePatientForm.tsx

when I create a new patient it get kicked back to something like this:
```
https://app.boson.health/patients?reload=pat_01GSE0VR7SG3QKNNV82A75AJZ3-01GSE0VRBKWQ4ACDG2RFWJ4P6G 
```
which when I refresh breaks the list populating 1 out of 3 ish times
but this doesn't break
```
https://app.boson.health/patients
```
Task Ref https://www.notion.so/photons/Adding-new-patient-loads-an-empty-patient-list-on-success-80019255ab964755bdeadf6faeeb80d1?pvs=4

nix query string

---

apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/components/LocalPickup.tsx
apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/components/Pharmacy.tsx
apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/index.tsx
apps/app/src/views/routes/Order.tsx

I missed this while moving around the pharmacy selection component. I just need to reset pharmacy selection when the tab changes so that it doesn't submit with the pharmacyId even on send to patient.

Fix order not sending to patient

---

packages/elements/package.json
packages/elements/src/store.ts

Weekend was getting a bump in "login required" errors after upgrading to elements [0.0.87](https://github.com/Photon-Health/client/releases/tag/%40photonhealth%2Felements_v0.0.87) permissions check.
The reason is we needed to wrap `await this.sdk.authentication.getAccessToken();` in a try catch in `checkSessions`.

Try getAccessToken

---

apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/index.tsx

We had previously hidden send to patient on neutron and photon due to an accidental merge. This didn't get reverted in our recent deploy. 
Note: It's also hidden on photon. So we'll want to catch this in the large deploy PR.

Show send to patient

---

packages/elements/index.html
packages/elements/package.json
packages/elements/src/photon-button/index.tsx
packages/elements/src/photon-checkbox/index.tsx
packages/elements/src/photon-form-wrapper/index.tsx
packages/elements/src/photon-multirx-form-wrapper/index.tsx
packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
packages/elements/src/photon-patient-dialog/index.tsx

- Fix button widths for mobile
min width 338
regular desktop
ref https://www.notion.so/photons/Improve-layouts-for-mobile-layouts-40b89c1556c843a4b7fb91c00e003d51?pvs=4
- no empty spinner button 
should be 
- fix form wrapper not being min height 100vh
- fix layout of dispense as written optional breaking on small modals and advanced search right aligned

Fix Mobile buttons

---

packages/elements/src/photon-dropdown/index.tsx
packages/elements/src/stores/patient.ts

If `r.at(-1)` isn't a function, we should check it:
```
a?.at(-1)?.isIntersecting && props.hasMore
```
task ref https://www.notion.so/photons/Request-Error-r-at-1-for-Weekend-6ccd91e3c55d481c844f0b0182aaa743?pvs=4

Make sure "at" exists

---

apps/app/src/views/components/TablePage.tsx
apps/app/src/views/routes/Prescriptions.tsx

On the prescriptions page there is now a filter that allows you to select between none, status active, status depleted, status expired. Also it adds a query string for the filter, works or refresh. Looks good on mobile (I think).
📽
https://www.loom.com/share/bd468ad6651d448894a7a41774280a33
task Ref https://www.notion.so/photons/Status-of-the-prescription-Filter-868fbe55da3e438ba4926399be1aab7d?pvs=4
Shout out to @photonsFardad for quick turn around providing the API to filter by prescription state

Prescriptions Status Filter

---

apps/app/src/views/routes/NewOrder/components/OrderForm.tsx
apps/app/src/views/routes/NewOrder/components/PatientAddressCard.tsx

task ref https://www.notion.so/photons/Add-save-to-patient-checkbox-for-address-input-on-create-order-3848b1334ebe492c8fe7334234d0db58?pvs=4

Save Patient's Address on New Order Page

---

apps/app/src/configs/fulfillment.neutron.ts
apps/app/src/configs/fulfillment.photon.ts

To make the send to patient fulfillment option available to the whole MoPed org

Enable send to patient for all MoPed prescribers

---

packages/elements/package.json
packages/elements/src/photon-multirx-form-wrapper/index.tsx

https://www.loom.com/share/254886ee78e64d2c8a9e622ff0639fd3
[task ref ](https://www.notion.so/photons/Prevent-errors-with-saving-prescriptions-b79a137c671241c5b8f041a23db1fc8c?pvs=4)

Elements: Add Confirmation to save prescription only

---

packages/react/package.json
packages/sdk/package.json

NPM installing sdk was not including the dist folder with the expected js file.

SDK: fix NPM publish

---

packages/elements/package.json
packages/elements/src/photon-card/index.tsx
packages/elements/src/photon-checkbox/index.tsx
packages/elements/src/photon-dropdown/index.tsx
packages/elements/src/photon-form-wrapper/index.tsx
packages/elements/src/photon-multirx-form-wrapper/index.tsx
packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
packages/elements/src/photon-multirx-form/index.tsx
packages/elements/src/photon-number-input/index.tsx
packages/elements/src/photon-phone-input/index.tsx
packages/elements/src/photon-textarea/index.tsx

cc @mrado1 
- reduce padding around the form 
- reduce card padding
- checkboxes align to the top not center
- "advanced search" should be under treatment on mobile when stacked
- remove gap when on mobile, it adds weird spacing when stacked in column
before:
after:

Prescribe Workflow mobile Layout issues

---

apps/app/src/model/fragments.ts
apps/app/src/views/routes/NewOrder/components/OrderForm.tsx
apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/index.tsx

The pharmacy selector was showing a preferred pickup pharmacy for a peachy patient when they only have mail order enabled.
After changes:
https://user-images.githubusercontent.com/3934326/227646750-be8d4976-e453-4be0-96ea-d75205c0efce.mov

fix(pharmacy selector): showing preferred pickup when only mail order is enabled

---

packages/elements/src/photon-multirx-form/components/DraftPrescriptionCard.tsx
packages/elements/src/photon-multirx-form/index.tsx

If the prescribe workflow has `template-ids` the prescribe form is hidden. This will hide the ability to edit the prescription if the prescriber clicks the edit button.
Once the form is opened it can't be closed again.

Elements: allow for editing preconfigured template-ids

---

packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx

Elements: Fix dosage button layout on mobile

---

packages/elements/src/photon-med-search/index.tsx

Elements: Medication Search needs wider layout

---

apps/app/src/hooks/usePrevious.ts
apps/app/src/views/routes/NewOrder/components/OrderForm.tsx
apps/app/src/views/routes/NewOrder/components/PatientAddressCard.tsx
packages/elements/src/photon-patient-form/index.tsx
packages/elements/src/validators/index.ts

- Elements: fixes validation on the update / create so that incorrect zip codes don't get introduced
- zip codes use the format of either 12345 or 12345-1234
- App: the address form will open up and display the error if theres something blocking sending the order
Can use the below patient to test
closes #205

Display Blocking Order Address Errors

---

apps/app/src/views/routes/Order.tsx
apps/app/src/views/routes/Patient.tsx
apps/app/src/views/routes/Prescription.tsx

This prevents an incorrect patient, order, or prescription ID from crashing the app:
closes #71

Handle non-existent entities

---

apps/app/src/App.tsx
apps/app/src/views/routes/PrescriptionForm.tsx

Attach one or many template ids when creating a new prescription in app.
```
/prescriptions/new?templateIds=tmp_01GQG3RD334GX1Z2Z2XXB59BM8,tmp_01GQGFHBZ8P0H52N62JKPBCHJH
```
cc @ottosipe

Add Template Ids to New Prescription via Query Param

---

package-lock.json
packages/elements/package.json
packages/elements/src/photon-multirx-form/components/PatientCard.tsx
packages/elements/src/photon-multirx-form/index.tsx

You can set the address like so:
``` jsx
function Photon() {
const address = {
postalCode: '11201',
street1: '123 street st',
state: 'NY',
city: 'Brooklyn',
};
return (
<photon-prescribe-workflow
patient-id="pat_01G8VFW0X44YCW8KW7FW3FC0ZT"
enable-order="true"
address={JSON.stringify(address)}
/>
);
}
```
If address is set, it will hide the ability for prescribers to set the address:

Ability to set Address in Prescribe Workflow 

---

packages/elements/package.json
packages/elements/src/photon-multirx-form/index.tsx
packages/elements/src/stores/form.ts

With many of our forms hidden if preset with values, prescribers are getting in a stuck state where nothing happens on validation error.

Display Validation Errors

---

packages/elements/package.json
packages/elements/src/photon-multirx-form/components/PatientCard.tsx
packages/elements/src/photon-multirx-form/index.tsx

If the patient request in `PatientCard` came back with an empty {} for address, it was setting `address` in the store which was failing validation. Even though the address that would have ultimately been passed was from props, the validation was failing so never making it to the mutation.
Now, there's a flag to not update the patient's address to the store if address is passed as a prop AND the prop address is set to the store on mount for good measure.

Prescribe Workflow Address needs to be Added to Store for Validation

---

package-lock.json
packages/elements/package.json
packages/elements/src/photon-treatment-select/index.tsx
packages/elements/src/stores/catalog.ts

Choosing to display the template name before the treatment name, my thinking is to me to lead with the disambiguation. 
Caveat:
When selected, we are passing around the treatment data, so when we display it in the selector or in Pending Prescriptions section it doesn't have access to the template data at the moment.

Display Template Name

---

package-lock.json
packages/elements/src/photon-multirx-form/components/PatientCard.tsx
packages/elements/src/photon-patient-select/index.tsx
packages/elements/src/utils.ts

``` html
<photon-prescribe-workflow patient-id="pat_01GQ0XFBHSH3YXN936A2D2SD7Y"></photon-prescribe-workflow>
```
Tests
closes #256

Hide Patient Dropdown if Patient ID is passed

---

packages/elements/package.json
packages/elements/src/photon-med-search-dialog/index.tsx

If you re add a medication to the catalog that already exists it throws an error. This handles it silently.

Handle error if medication already added to catalog

---

apps/app/src/views/components/NameView.tsx
apps/app/src/views/components/Nav.tsx
apps/app/src/views/components/PharmacyNameView.tsx
apps/app/src/views/components/UserProfile.tsx

https://photon-health.sentry.io/issues/4052433134/?project=6641717&query=&referrer=issue-stream&statsPeriod=1h&stream_index=0
from the issue we can see `AvatarName` which is a Chakra component:
https://github.com/chakra-ui/chakra-ui/blob/997e3083f282f73c8a85bb1e612e1062f1f6d715/packages/components/avatar/src/avatar-name.tsx
The logging in grabbing the initials is:
```
const names = name.split(" ")
const firstName = names.at(0) ?? ""
```
I'm not sure what would not error on  `.split` but fails on `.at`

r.at (🐀) is not a function

---

package-lock.json
package.json

Chakra recently added `.at(0)`[ (more info)](https://github.com/Photon-Health/client/pull/274) this rolls back and locks a previous version that doesn't. Was breaking on a outdated Safari.
https://caniuse.com/?search=array.at

Lock Chakra

---

apps/app/src/views/routes/Prescription.tsx
apps/app/src/views/routes/Prescriptions.tsx

Surface the same state description tooltips from prescriptions list on single prescription view

Add state tooltips to prescription page

---

packages/elements/index.html
packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx

Layout in a container on desktop breaks:
Unfortunately Shoelace is applying some baffling styles that makes it hard to fix this. Worked on it for over an hour but no luck, so fell back to the previous working (but not ideal) layout for now.
closes #300

Fix Calculator Layout

---

.github/workflows/npm-publish.yml
packages/react/package.json
packages/sdk/package.json

Had some success, npm package got published, but the tag failed:
```
Creating GitHub release for packages/react...
Committer identity unknown
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: empty ident name (for <runner@fv-az1259-722.igmqbu2b14eejbj4jfxtszghqh.cx.internal.cloudapp.net>) not allowed
Error: Process completed with exit code 128.
```
https://github.com/Photon-Health/client/actions/runs/5081929140/jobs/9130973665

Add Git name and email for NPM Publish action

---

packages/elements/src/photon-form-wrapper/index.tsx

This technically shouldn't happen with our checks, so going to look into this in a separate ticket.
Ticket to fix eslint https://github.com/Photon-Health/client/issues/359
closes #355

Remove From Props

---

packages/react/package.json
packages/sdk/package.json
packages/sdk/src/lib.ts
packages/sdk/src/utils.ts

- change Apollo's global fetch policy to `cache-first`
- `makeQuery`'s fetch policy will now default to `network-only` so that the existing methods fetch & store data as before
- expose apollo client
My thinking is that I'll use Apollo's query and mutations directly when building the pharmacy select feature.

SDK ground work

---

apps/app/src/views/routes/NewOrder/components/OrderForm.tsx
apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/components/MailOrder.tsx

Closes #352 
Initial fulfillment type was not getting set when only mail order is enabled, this fixes that.
Tested with all variations of enabled types.

Fix peachy sending to patient

---

apps/patient/src/components/Nav.tsx

Closes [issue](https://www.notion.so/photons/Help-link-opens-email-instead-of-sms-743b6cc1b27041c9b9adf5ec049b7061?pvs=4)

Fix nav help-link going to email not sms

---

packages/elements/src/photon-dialog/index.tsx
packages/elements/src/photon-form-wrapper/index.tsx
packages/elements/src/photon-med-search-dialog/index.tsx
packages/elements/src/photon-multirx-form-wrapper/index.tsx
packages/elements/src/photon-multirx-form/components/DraftPrescriptionCard.tsx

https://www.notion.so/photons/Closing-Dialog-Submits-Form-0b7f529aacb642e39cc9e77866bddf12?pvs=4
Added a third type of event handler to our existing dialog element:
```
'photon-dialog-confirmed' | 'photon-dialog-alt' | 'photon-dialog-canceled'
```
in most cases `alt` and `canceled` are the same affect, but in the case of the dialog in the ticket above we want the alt button to  only create a subscription  and the X button to close the dialog.

Closing Dialog Submits Form

---

packages/elements/src/photon-dropdown/index.tsx

Resulting from this [update](https://github.com/Photon-Health/client/commit/afa79f76441b0123f56fa48ba9d148b174a0f39d) when I was updating lint action for repo, somehow this filter got dropped.
https://www.notion.so/photons/Medication-Dropdown-Grouping-fedfe8903df7468f9dcb8c50ea796598?pvs=4

Revert Dropdown Grouping

---

packages/components/src/systems/PharmacySelect/index.tsx
packages/elements/package.json

Switching from send to patient to local pharmacy sets the pharmacy id. Then, when you switch back it was not being unset.

Unset Pharmacy ID for "Send to Patient" Tab

---

apps/app/src/model/fragments.ts
apps/app/src/views/routes/Settings/components/TemplateForm/index.tsx
apps/app/src/views/routes/Settings/components/TemplateForm/utils.ts
apps/app/src/views/routes/Settings/views/TemplateTab.tsx
packages/sdk/src/clinical/prescriptionTemplate.ts

Cleaned up the template rows, highlight if it has a name.
Create and Edit Form now has a template name area:
https://www.notion.so/photons/Ability-to-add-and-update-template-names-1923639a26914fed8a7ffab0fa349526?pvs=4

Add and Edit Template Names In App

---

apps/app/src/views/components/OrderStatusBadge.tsx
apps/app/src/views/routes/Order.tsx
apps/app/src/views/routes/Orders.tsx
apps/app/src/views/routes/Patient.tsx
apps/app/src/views/routes/Prescription.tsx
packages/sdk/src/fragments.ts

https://www.notion.so/photons/Add-Order-table-to-page-8261841d7c4c4e9abd2e8a28d6a52c36?pvs=4
UPDATE
- now has reusable order status badge
- [flattens duplicate fills](https://www.notion.so/photons/Collapse-fills-on-order-screen-that-go-to-the-same-prescription-7bd48025091242f3a0359f5856632543?pvs=4) on order and rx pages
- Fill Id added on the [Order page Fills](https://www.notion.so/photons/Display-fill-id-on-order-view-58e2e21fd3754c8bb3cf3a1bb3a05a57?pvs=4)
when routing
when it has order status

Add Order table to page

---

apps/app/src/views/components/CopyText.tsx
apps/app/src/views/components/InfoGrid.tsx
apps/app/src/views/components/Page.tsx
apps/app/src/views/routes/Order.tsx
apps/app/src/views/routes/Patient.tsx
apps/app/src/views/routes/Prescription.tsx

https://www.notion.so/photons/Rx-Page-Info-Hierarchy-e155b8dba73046d390a26dc1e977d9ef?pvs=4
(bonus New)
- <img src="https://github.com/Photon-Health/client/assets/700617/c2101418-9197-4fd1-b012-45361b1b9f30" width="200" />

Update Rx Hierarchy

---

apps/app/src/views/components/Auth.tsx
apps/app/src/views/routes/Settings/components/Credentials.tsx
apps/app/src/views/routes/Settings/index.tsx

Placement of Auth Token got swapped with Add Provider
This opens up a form into a new tab with Org name and id as hidden fields on the form. When you're done submitting, you'll see in the `#new-provider` slack channel:

Add Providers with Typeform

---

apps/app/src/views/routes/Prescription.tsx
apps/app/src/views/routes/Prescriptions.tsx

Fixes: [Remove ability to create an order for a depleted prescription](https://www.notion.so/photons/Remove-ability-to-create-an-order-for-a-depleted-prescription-c039f447647541d8875ede200610a1fd) 
In depleted, create order
- disabled on prescriptions table
- disabled on prescription view

Disable create order when rx depleted

---

apps/app/src/views/routes/Order.tsx

ref
https://www.notion.so/photons/Order-Cancel-button-should-be-hidden-if-order-fulfillment-is-marked-shipped-cf4b613624cb4985b29736feb056df0c?pvs=4

Order Cancel button should be hidden if order fulfillment is marked shipped

---

apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/components/MailOrder.tsx

If there's one mail order option it should auto select the only option. The problem is it had a weird race condition unselecting while still being visible when you switch tabs.
https://www.notion.so/photons/Mail-order-pharmacy-selection-persisting-in-local-pickup-tab-ebd3e8a4279a4b94a06c388daef5cec4?pvs=4

Fix Mail order pharmacy selection persisting in local pickup tab

---

apps/patient/src/graphql/queries.ts
apps/patient/src/utils/text.ts
apps/patient/src/views/Review.tsx

Instructions on prescriptions can be confusing for people (like myself) that aren’t familiar with medical terminology. For example, not everyone knows that “Take 1 BID PO” means “Take one tablet twice a day, with meals.” It's the pharmacists job to make this sort of translation. So we're removing to not confuse people.
[See ticket](https://www.notion.so/photons/Remove-instructions-on-patient-rx-review-00d4ba992f4e4e73b03a886785a2415e)

Remove patient instructions on rx review

---

packages/components/dev/App.tsx
packages/components/src/index.ts
packages/components/src/particles/Text/index.tsx
packages/components/src/systems/DraftPrescriptions/index.tsx
packages/components/src/systems/DraftPrescriptions/utils/generateDraftPrescription.ts
packages/elements/index.html
packages/elements/package.json
packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
packages/elements/src/photon-multirx-form/components/DraftPrescriptionCard.tsx
packages/elements/src/photon-multirx-form/index.tsx

I'm starting to chip away at moving functionality and styling out of `packages/elements` and into `packages/components`... thought this would be a nice small visual change.
The `DraftPrescriptions` component handles its own querying and moves away from using the SDK methods.
I want to test this in a few different scenarios to make sure I didn't rollback any functionality. Caught a few minor bugs on the way.

Draft Prescription Refactor

---

apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/components/LocalPickup.tsx
apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/components/Pharmacy.tsx
apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/components/SendToPatient.tsx
apps/patient/src/components/PharmacyCard.tsx
packages/components/src/systems/PharmacySelect/PatientDetails.tsx
packages/components/src/utils/formatAddress.ts
packages/components/src/utils/toTitleCase.ts
packages/elements/package.json

https://www.notion.so/photons/Preferred-Pharm-on-Send-To-Patient-Card-7eac7940022a4f7fbeb898f26cb296aa?pvs=4
In Elements, top is a patient without preferred, bottom is a patient with preferred set:
In the Clinical App (Chakra):

Preferred Pharmacy in Send to Patient Card

---

apps/app/declarations/dob-to-age.d.ts
apps/app/src/views/routes/Orders.tsx
apps/app/src/views/routes/Patients.tsx
apps/app/src/views/routes/Prescriptions.tsx
apps/app/tsconfig.json

Caveat this doesn't solve repetitive auth issue on page load. 
**~57%** improvement on fetch time, from ~1400ms to ~600ms
**~82%** improvement on fetch time, from ~1294ms to ~225ms
no improvement, about the same

Improved fetch times on list pages (rxs, orders, patients)

---

apps/patient/src/views/Status.tsx

Hide the set picked up footer on the status view til the order has been set received.
[More details](https://www.notion.so/photons/Patient-s-accidentally-setting-picked-up-e5a0103d90324c98ba17dc45fe274b4f?pvs=4)

Hide option to set picked up til order received

---

packages/settings/src/lib/neutron.ts

I was using the photon org id on neutron

Fix carbon health branding on neutron

---

packages/settings/src/lib/neutron.ts

To use the correct org id for carbon in neutron org settings

Neutron: Fix carbon health branding on neutron

---

apps/patient/src/data/demoOrder.ts

Newco is unbranded on neutron rn, that's due to my demo data using the boson newco orgId

Fix neutron newco demo branding

---

apps/app/src/views/routes/PrescriptionForm.tsx
packages/components/src/systems/DoseCalculator/components/UnitSelect.tsx
packages/components/src/systems/DoseCalculator/index.tsx
packages/components/src/systems/PatientInfo/index.tsx
packages/elements/src/photon-multirx-form-wrapper/index.tsx
packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
packages/elements/src/photon-multirx-form/components/PatientCard.tsx
packages/elements/src/photon-multirx-form/index.tsx

EG
`/prescriptions/new?&weight=50&weightUnit=kg`
Weight unit defaults to pounds, but you can override by adding `weightUnit=kg`

Add kg for patient weight param 

---

packages/elements/package.json
packages/elements/src/photon-authorized/index.tsx

don't love the nested fallback `Show` ... but Solid wants to have a single return unlike React

Better Auth Error messages Elements

---

packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx

patient weight is overwritten when a template with notes is selected. 
https://www.loom.com/share/e57297f14ff94838bed699017c782e8f
try it out:
`/prescriptions/new?patientId=pat_01H4S2QQQGF4T7G3F4N0QE2SVC&weight=105`
also, for some reason things like `props.store.treatment?.value` were being written like `props.store['treatment']?.value`

Dont overwrite weight

---

packages/components/src/systems/PharmacySearch/index.tsx
packages/components/src/systems/PharmacySelect/index.tsx

I fixed an issue, but it broke something else. Pharmacy Ids weren't being reset when switching to a tab the second time.
also, bonus the location goes to a new line on smoller screens:

Fix Pharmacy selection between tabs

---

apps/app/src/App.tsx
apps/app/src/views/components/Zendesk.tsx
apps/app/tsconfig.json
apps/app/types/zendesk.d.ts
packages/components/src/particles/Dialog/index.tsx

This sets a `clinical` tag and some user fields set programmatically:
we're still seeing the the name:
But this can't be solved until we authenticate a users:
https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/sdks/web/enabling_auth_visitors/?_ga=2.226550238.290978968.1698699914-805225644.1697815467
https://support.zendesk.com/hc/en-us/articles/4411666638746

Add Meta Data to Zendesk Tickets

---

packages/elements/src/photon-multirx-form/components/PatientCard.tsx
packages/elements/src/photon-multirx-form/index.tsx

When we released the combined order/presccription view, we added a requirement to set address. That was carried over to the single prescription workflow, where an address _should not_ be required to prescribe

Hide address form on prescription only form

---

packages/elements/package.json
packages/elements/src/photon-client/index.tsx

Element styles are leaking into a customer's styles. Although Shadow DOM usually prevents this, our client which imports styles wraps their code which could be the issue.
https://photonhealth.slack.com/archives/C03TRQ4NLE5/p1699918542888819

Remove client styles

---

apps/app/src/views/routes/Prescriptions.tsx

Clicking the disabled create order icon button on prescriptions list will still take you to the create order page.
Added toast on click:

Fix disabled create order still allowing creation

---

apps/patient/src/views/Status.tsx

Noticed errors on pizza tracker "get directions" in Datadog. Looks like `focus()` is not needed here. Removing has the same behavior of opening in new tab but appears more reliable.
MDN on focus(): 
> It may fail due to user settings and the window isn't guaranteed to be frontmost before this method returns.

Fix get directions intermittently failing

---

packages/components/src/systems/PatientInfo/index.tsx

Noticed that the Text web comp doesn't include any text elements other than span so that mask isn't getting applied to anything. This just puts it back up top where it applies to everything in the card.

Update masking on patient card

---

apps/app/src/views/routes/Patients.tsx

After creating a patient (in elements), we navigate back to the patient list page but the new patient isn't there. This refetches the list.

Refetch Patient List

---

packages/elements/src/photon-client/index.tsx
packages/sdk/src/lib.ts
packages/sdk/tsconfig.json

Here's a suggestion for how we can send the elements+sdk versions. We should then make sure we're logging this on the BE and then generate a metrics view to show which versions are being used by which customers.
I'm open to other approaches as well, this just seemed like the minimal set of changes.
We'd have to have our customers upgrade their libraries to get these changes.
One other approach would be, instead of passing in the elements version to the `PhotonClient` constructor, we could attach something to the global context or something.

[Suggestion] Attach SDK and Elements versions to requests

---

apps/app/src/configs/auth.ts
apps/app/src/views/routes/SelectOrg.tsx
package-lock.json
package.json
packages/sdk/package.json
packages/sdk/src/auth.ts
packages/sdk/src/lib.ts

Was able to get auth to work on safari (and presumably other browser with ITP (Intelligent Tracking Prevention) enabled ). The key was using [Refresh Token Rotation](https://auth0.com/docs/secure/tokens/refresh-tokens/refresh-token-rotation) and setting storage to be done in localstorage instead of cookies.
I also upgraded the version of auth0 we were using but this didnt end up having an impact, but left it as it took some work to get upgraded and we were very behind

Fix auth on browsers with ITP (i.e. safari)

---

apps/patient/src/components/StatusStepper.tsx
apps/patient/src/utils/text.ts

This fixes an issue for the mail order status stepper not finding the right states. I was mapping what we do have to different states for courier and mail order, kind of like what we might have someday, but that's superfluous so I'm just removing and showing different copy for each state based on fulfillment type.

Fix status stepper states

---

apps/patient/src/App.tsx
apps/patient/src/utils/text.ts
apps/patient/src/views/Review.tsx
apps/patient/src/views/Urgency.tsx

Re-enable our urgency selection view. It sits between review and pharmacy selection. I'm also tracking these selections in datadog with a new custom event.
https://github.com/Photon-Health/client/assets/3934326/c6c56866-587f-4c67-ba37-1a8944516058
Example export of selection data:

Enable urgency selection

---

packages/sdk/src/utils.ts

This slash looks to be causing the settings users tables to not load.

Remove extra trailing slash from photon api url

---

packages/elements/src/photon-client/index.tsx

For sesame (and anyone else I guess). We'll allow putting in a `userId` which we'll then check against **at initial render time** against the `sub`. For google that takes the form of `google-oauth2|<string>` and we match against that string. For Sesame, it looks like `oidc|Sesame-2|2a8a5791-292a-4eeb-8169-ca9b7fa3059b` so we'll expect `2a8a5791-292a-4eeb-8169-ca9b7fa3059b`
**At initial render time** means that if they simply change the props **nothing will happen**. To get around this, they should wrap it in a div with a key like
```tsx
<div key={userId}>
<photon-client userId={userId}>
<photon-prescribe-workflow/>
</photon-client>
</div>
```
Note that we need to also update the docs.

logout on userID diff

---

packages/elements/index.html
packages/elements/src/photon-multirx-form/index.tsx

- allows customers to add an external id to be associated with the created order
- bumps version to 0.5.3

External Order ID prop on Prescribe Element

---

packages/components/src/systems/RecentOrders/RecentOrders.tsx

1. creates an order for a patient
2. navigates back to prescribe workflow without refreshing
3. Recent orders card doesn't show for patient
4. refresh page
5. Recent order card appears for patient

Fixes Recent Orders Card grabbing cached data

---

packages/sdk/src/auth.ts

We _think_ that the bug where you can be seemingly logged in but not actually is caused by `getAccessToken` returning null for the token. To repro, you can open two tabs, log in, then log out of one and navigate around in the other tab. In previous versions you would see a `Login Required` error message. Now you should get redirected to the login page.
We use `loginWithRedirect` so that if there's auto-login set up, it _should_ just re-execute the SSO handshake

hopefully fix auth0 login_required bug

---

.github/workflows/merge-bot.yml

If the `ready` label is attached to the PR, the merge bot will succeed. If the `ready` label is not attached to the PR, the merge bot will fail (instead of skip) and will disable auto-merge (in case it was already labeled ready). 
This is so we can include a rule in `neutron/photon` that requires merge bot to pass. In the past, it was only required to not fail.

fail if not ready

---

packages/settings/src/lib/neutron.ts

We were using the org id of a different sandbox account (was setup earlier, but then for some reason they had a whole other org setup 🤷 )

Fix pine medical org id

---

packages/components/src/systems/DraftPrescriptions/index.tsx
packages/components/src/systems/RecentOrders/RecentOrders.tsx
packages/components/src/systems/RecentOrders/RecentOrdersCombineDialog.tsx
packages/components/src/systems/RecentOrders/RecentOrdersIssueDialog.tsx
packages/components/src/utils/createMutation.ts
packages/components/src/utils/createQuery.ts
packages/components/src/utils/uniqueFills.ts

This ports over the `createQuery` and `createMutation` functions from [solid-apollo](https://github.com/merged-js/solid-apollo).
I've updated the `RecentOrders` to demonstrate how to use both functions.

Solid query and mutation

---

apps/app/src/views/routes/SelectOrg.tsx

Maybe something is hitting this? 
Would explain why:
- We don't see this as much as other people
- When we do see this, it redirects us to `<SelectOrg/>`

in <SelectOrg />, pass orgId to login if theres only one organization

---

apps/patient/src/views/ReadyBy.tsx

We're looking for a reasonable cut-off. If they select a time that's 5min away, there's no way we can fill that. 30min seems like a good place to start.

Disable ready by option if it's within 30 minutes

---

apps/app/src/views/routes/Orders.tsx
apps/app/src/views/routes/Patient.tsx

Orders with multiple meds were missing comma separator

Fix multi-medication order names missing comma

---

apps/patient/src/views/ReadyBy.tsx

Fooled me twice those bugga's! 🤕 
The radio components border was still selectable causing folks to still select disabled times.

Fix disabled ready by radio border still selectable

---

packages/elements/package.json
packages/elements/src/photon-client/photon-client-component.tsx
packages/elements/src/photon-multirx-form/photon-prescribe-workflow.tsx
packages/elements/src/store.ts

A log in was being triggered immediately on page load even if the flag `auto-login="false"` on the `photon-client`.

Fix Auto Login Flag

---

.github/workflows/upload-source-maps-to-datadog.yml

It was looking at root where there's another package.json, we need the app specific one to get the correct name and version.

Fix package.json paths in source map upload

---

.github/workflows/upload-source-maps-to-datadog.yml

It's still having trouble getting the env, since our target branches are boson, neutron, photon, I think we can just use `github.ref`.

Use `github.ref` to get env for source map upload

---

packages/elements/package.json
packages/elements/src/photon-multirx-form/photon-prescribe-workflow.tsx

This addresses the Blueberry comment [here](https://blueberrymed.slack.com/docs/T6AM2J4UD/F06QGB4328G?focus_section_id=temp:C:RUT638e4be724cd48db9b62ec036): `Error events are emitted with empty errors arrays.`
We are sending event messages, tho this situation we are emitting an event without details. 
I'd opt for removing this error since there technically isn't one, we're just letting them know that they have another order that this can be combined with. And I think the modal gives that context well.

Remove combine modal error

---

apps/patient/src/api/internal.ts
apps/patient/src/graphql/mutations.ts
apps/patient/src/views/Pharmacy.tsx
apps/patient/src/views/Status.tsx

1. There was an error introduced with the reroute failed error that is fixed here
2. I simplified the logic about how the status page knows if an order reroute was just attempted, it also allows now for a reroute after the first selection

Fix Reroute Error + Can reroute on First Pharmacy Selection

---

apps/patient/src/views/ReadyBy.tsx

This was highlighted by Jomi, change is to prevent accidental selections.
[See ticket](https://www.notion.so/photons/Dismiss-Next-button-when-a-user-toggles-between-Today-Tomorrow-29c2d5bf3c014ce8a8c9a1e1a1742afd?pvs=4)
Example of footer hiding on day change...
https://github.com/Photon-Health/client/assets/3934326/2dc36f6c-6100-4e51-a44d-368f65a0e2bf

Disable Next button when readyBy day is changed

---

apps/patient/src/views/ReadyBy.tsx

Noticed in sessions that on prod where the blue "This is not a real prescription" banner shows and the readyBy options extend past the bottom of the page because it's an extra small screen (iPhone SE), that there's a gap above the sticky today/tomorrow section.
Removing this gap...

Fix gap above today/tomorrow section on small screens

---

apps/patient/src/components/PrescriptionsList.tsx

Rx's were missing the collapse arrow at the top right of the accordion items. Just re-adding that.
After:

Fix review rx accordion collapse

---

packages/settings/src/lib/neutron.ts

To test walgreens on neutron before blueberry launch on production.
Also disabled topRankedCostco on test org.

Enable `topRankedWalgreens` on neutron

---

packages/settings/src/lib/photon.ts

This will actually start to surface walgreens at the top for Blueberry patients.

Enable `topRankedWalgreens` for Blueberry on photon

---

packages/settings/src/lib/photon.ts

This is for housekeeping so that boson and neutron have what is currently on photon

Disable topRankedWalgreens for Blueberry on production

---

packages/settings/src/lib/photon.ts

Re-enabling the Walgreens urgency pilot for Blueberry Pediatrics

Re-enable `topRankedWalgreens` for Blueberry

---

packages/settings/src/lib/photon.ts

Though the previous deployment enabled this, our rollback overrode this change.

Set `topRankedWalgreens` on photon

---

apps/app/public/index.html
apps/patient/public/index.html
packages/components/src/systems/LocationSelect/index.tsx
packages/components/src/systems/PharmacySearch/index.tsx
packages/components/src/utils/getLocations.ts
packages/components/src/utils/loadGoogleScript.ts

Our Google maps initialization is outdated, `callback` is now required, `async` is highly recommended. 
Fixes [this error](https://photonhealth.slack.com/archives/C03BV7ZBHLM/p1713284826939819)
> Google Maps JavaScript API error: NotLoadingAPIFromGoogleMapsError
https://developers.google.com/maps/documentation/javascript/error-messages#not-loading-api-from-google-maps-error
While fixing that, I noticed that latlng can be undefined in getLocations, added a check. Should revisit to see why it was passed in undefined, but it wasn't clear exactly where that's happening so this resolves for now.

Fix location search console errors

---

apps/patient/src/views/Main.tsx

This error has been spammy forever, now it's polluting frontend DataDog errors. We don't act on these, so removing.

Remove unnecessary console error

---

apps/app/public/index.html
apps/patient/public/index.html
packages/components/src/utils/loadGoogleScript.ts

Google isn't loading in time for component render on boson after recent google script tag update, removing optional async tags fixes this

Revert google async load

---

packages/elements/index.html
packages/elements/package.json
packages/elements/src/photon-multirx-form-wrapper/photon-multirx-form-wrapper-component.tsx
packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
packages/elements/src/photon-multirx-form/photon-prescribe-workflow-component.tsx
packages/elements/src/photon-multirx-form/photon-prescribe-workflow.tsx

This adds a new `general-notes="These are some notes"` to the prescribe elements. A customer was asking for a way to apply it to all Rxs, not just template overrides.
General Notes alongside a set patient weight
If you add only `weight="23"`:
When a template is selected, the template notes prepend to the general notes:

Add a general notes parameter to the prescribe element

---

packages/elements/src/photon-med-search/photon-med-search-component.tsx

On `/prescriptions/new`, we've been seeing `TypeError: Cannot read properties of null (reading &#x27;catalogs&#x27;)`, this was due to incorrect query being used in med search.

Fix err fetching catalogs in advanced search

---

apps/patient/src/api/internal.ts

This attempts to resolve our new highest frequency frontend error [details here](https://app.datadoghq.com/rum/error-tracking/issue/1f72a946-a6a7-11ed-b1c7-da7ad0900002?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1712340879416&to_ts=1713550475087&live=true). Impacting 3% of sessions.
> TypeError:
undefined is not an object (evaluating 't.t0.response.errors')
This double-checks that we have errors present before throwing one on our internal patient queries. I'm not sure exactly which one is causing most of these, but this'll tell us now.

Better error handling on internal patient queries

---

apps/patient/src/api/internal.ts
apps/patient/src/views/Pharmacy.tsx

This is another longstanding error that isn't an error. When there's no pharmacies near the patient we don't need to throw an error, we can just notify the patient.

Don't error when no pharmacies are present

---

packages/elements/package.json
packages/elements/src/photon-client/photon-client-component.tsx
packages/elements/src/utils.ts

We have an issue where a customer is has an [Auth0 instance that's in conflict with our Element's instance](https://photonhealth.slack.com/archives/C06DCU1DTMJ/p1713253957783859). What's causing the issue is that both instances are picking up on the redirect url's params. So to solve this I've added a hardcoded param to our elements that won't do any checks if it's coming from the parent.
Any customer that is using their own Auth0 login will need to set `skipRedirectCallback` to look for the presence of `photon=true`:
``` tsx
<Auth0Provider
domain="customer-auth-domain"
clientId="customer-auth-client-id"
authorizationParams={{
redirect_uri: `${window.location.origin}`
}}
skipRedirectCallback={window.location.href.includes('photon=true')}
>
```
Then, when as high up in the customer's …

Two Auth0 Providers

---

packages/elements/package.json
packages/elements/src/utils.ts

Deeplinking in the app was broken by this change:
https://github.com/Photon-Health/client/pull/1146/files
https://photonhealth.slack.com/archives/C02V18YAEE9/p1714751735133409
This condition was pretty shaky. I would rather something that looks like this:
``` ts
return (code || error) && state && photon;
```
but typescript was giving me 
```
Type 'string | (string | null)[] | null' is not assignable to type 'boolean'.
Type 'null' is not assignable to type 'boolean'.
```

Fix Deeplinking

---

packages/settings/src/lib/neutron.ts

Add Honeybee and TruePill as mail order options for GoalMD on neutron

Add mail order options for GoalMD sandbox

---

apps/app/buildspec.yml
apps/patient/buildspec.yml

This is step one of [setting up a repo in DD](https://app.datadoghq.com/source-code/setup/apm#configure):
1. Associate a git commit with your telemetry - this
2. Configure your repository - this is where we actually link our account
Without a repo configured we can't get human-readable source map previews in our issues.

Add Datadog vars for APM source code integration

---

apps/patient/src/views/Status.tsx

Small contrast fix on get directions btn

---

packages/elements/package.json

The RC works for our [customer](https://photonhealth.slack.com/archives/C06DCU1DTMJ/p1715867303641579?thread_ts=1713253957.783859&cid=C06DCU1DTMJ), so we can safely bump the version witch includes the following changes:
- https://github.com/Photon-Health/client/pull/1159
- https://github.com/Photon-Health/client/pull/1174
- https://github.com/Photon-Health/client/pull/1175

Bump Elements Version

---

apps/patient/src/views/Pharmacy.tsx

Quirk that if we close the set location modal without location, it resets the whole UI to this...

Fix pharmacy selection UI resetting if modal closed without location

---

.github/workflows/npm-publish.yml

We don't want a customer's app pull in work we're still vetting.

Our Release Candidates should not be tagged as latest

---

apps/app/src/views/routes/PrescriptionForm.tsx
packages/components/src/systems/PatientMedHistory/index.tsx
packages/elements/package.json
packages/elements/src/index.ts
packages/elements/src/photon-med-history/index.tsx
packages/elements/src/photon-med-history/photon-med-history.tsx
packages/elements/src/photon-multirx-form-wrapper/photon-multirx-form-wrapper-component.tsx
packages/elements/src/photon-multirx-form/components/PatientCard.tsx
packages/elements/src/photon-multirx-form/photon-prescribe-workflow-component.tsx
packages/elements/src/photon-multirx-form/photon-prescribe-workflow.tsx

Can be used like:
``` html
<photon-med-history patient-id="pat_01GQ0XFBHSH3YXN936A2D2SD7Y"></photon-med-history>
```
Request Reference https://photonhealth.slack.com/archives/C033T9N949M/p1716470078960499
ALSO, this removes[ auto enabled linking to the Photon App in the Medical history card rows. ](https://www.notion.so/photons/Embed-should-not-link-to-Photon-App-8a0a939c032241bc8b0220cc730a624a?pvs=4) 
Because this change changes the functionality of the card to opt in to the links, Elements are getting a minor bump to `0.10.0`. We can also safely move forward with the RC because [what we were testing works.](https://photonhealth.slack.com/archives/C05LVD54ZC0/p1716495725050929)

Stand Alone Med History Card

---

apps/app/src/views/components/AdvancedDrugSearch.tsx
packages/elements/package.json
packages/elements/src/photon-checkbox/photon-checkbox-component.tsx
packages/elements/src/photon-med-search-dialog/photon-med-search-dialog-component.tsx
packages/elements/src/photon-med-search/photon-med-search-component.tsx

We saw a lot of providers repeatedly going to Advanced search to add medications. If we default add it to a customer's catalog we can mitigate that as the standard interface for adding medications.

Default Add Medication to Catalog From Advanced Search

---

packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
packages/elements/src/photon-multirx-form/util/clearForm.ts

Entering before the 0 in the example below creates "20", while entering after is "2". It's tripping up some providers, so let's just not have 0 as a helper defaulted on the "refills" section.
https://www.loom.com/share/0831d27fc52b45a19da2905b18d2e95a

"Refills" doesn't have a default

---

packages/components/src/particles/Tabs/Tabs.stories.tsx
packages/components/src/particles/Tabs/index.tsx
packages/components/src/systems/PharmacySelect/PharmacySelect.tsx
packages/elements/package.json

If "Send to Patient" isn't in the tabs of the Pharmacy Select card, the tab body didn't show up until the tab is clicked.
Ticket Ref
https://www.notion.so/photons/Mail-Order-Only-isn-t-showing-up-88562f784b8c4664a322d7719d1a3eb2?pvs=4

FIX: Mail Order Only Is Not showing Up in Pharmacy select Card

---

apps/app/src/views/routes/PrescriptionForm.tsx
package-lock.json
packages/elements/src/photon-multirx-form-wrapper/photon-multirx-form-wrapper-component.tsx

This was a [request by Tellescope](https://photonhealth.slack.com/archives/C0578R92FKP/p1717594405532649?thread_ts=1715291373.980139&cid=C0578R92FKP) to also pass in a pre-selected mail order pharmacy.

Add pharmacyId to deep link

---

apps/patient/public/index.html
apps/patient/src/index.tsx
apps/patient/src/views/Pharmacy.tsx
package-lock.json
package.json

To start getting a feel for how far down users are going into the list to find their pharmacy.
The reason why we're doing this with Google Analytics is so that we can pull this into Metabase.

Track selected pharmacy rank in list

---

apps/patient/public/index.html

Apparently since we're using react-ga4, we don't need to setup the usual google analytics tag in index.html. It handles that for us.

Remove unnecessary GA setup tag

---

apps/app/src/views/routes/Settings/components/templates/TemplateForm/components/RefillsInput.tsx
apps/app/src/views/routes/Settings/components/templates/TemplateForm/index.tsx
apps/app/src/views/routes/Settings/components/templates/TemplateForm/utils.ts

A provider said their template was defaulting to 10 refills instead of 1. Turns out it was a string adding to a number `"1" + 0`
Also, I picked up this ticket to have blank init values:
https://www.notion.so/photons/Template-Form-should-have-blank-defaults-ac3af176ae4740ce9b2e62caeb56eef5?pvs=4

Fixing refills in Templates

---

packages/components/src/systems/PharmacySearch/index.tsx

[Ticket](https://www.notion.so/photons/Infinite-Spinner-on-Local-Pickup-688be7d4510f49c8babfbb416011490f?pvs=4)
I wasn't directly able to replicate this issue. But by simulating a geocoder load fail the spinner did hang. So by handling asyncInterval hitting max loading attempts and conditionally setting location, the UI appears to be working as intended.
I want to check if Jessica (from Sesame) still has this issue after merging.

handle infinite spinner issue in local pickup tab

---

apps/patient/src/components/DemoCtaModal.tsx
apps/patient/src/views/Status.tsx

Also worth noting that you can re-open the modal by clicking "I picked up my prescriptions".

Add close btn to demo modal

---

apps/app/src/views/components/GuardDialog.tsx
apps/app/src/views/routes/Settings/components/invites/InviteItem.tsx

[Was gonna fix this](https://www.notion.so/photons/Resend-invite-should-retain-provider-details-41cad117c2124885a459628852757175?pvs=4) ticket of mine, but it was all good.
but I saw the confirm modal, its so big
now it's better

Confirm modal was too big

---

apps/patient/src/components/BrandedOptions.tsx

Small fix in case delivery is enabled but there are no options, for example if out of range of capsule or glp1's are present for sesame.
Fixes this

Hide delivery header if no options

---

packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx

Ticket Ref:
https://www.notion.so/photons/Prescriber-can-write-too-many-refills-c494b86437be4cb5ba861289a360b848?pvs=4
After speaking with Caitlyn and Shannon, we confirmed that 11 was the maximum amount of refills on a prescription.
and so...

Refills have a max of 11

---

apps/patient/src/App.tsx
apps/patient/src/views/Main.tsx

https://www.notion.so/photons/Screen-is-at-the-bottom-of-the-Status-Page-after-Pharmacy-Selection-ea8b0aa2772d40549ba8e09f47c39678
Required adopting new React Router v6 paradigm 🤷 
https://reactrouter.com/en/main/components/scroll-restoration
and
https://reactrouter.com/en/main/routers/picking-a-router

scroll to top on route change

---

apps/patient/src/components/BrandedPharmacyCard.tsx
apps/patient/src/components/PharmacyInfo.tsx
apps/patient/src/views/Pharmacy.tsx
package-lock.json
packages/settings/src/lib/neutron.ts
packages/settings/src/lib/photon.ts

We're running a similar delivery test to our recent Courier tests. This will also be for Sesame, but Amazon Pharmacy this time. Also note, this is mutually exclusive to the top ranked Costco option we are surfacing for Sesame GLP's.
Here's what the option looks like...

Enable local delivery Amazon Pharmacy test for sesame

---

apps/patient/src/api/internal.ts
apps/patient/src/views/Pharmacy.tsx

Right now we are returning costcos that are real far away (see below) for top ranked pharmacies like Costco we should limit the radius in search.

Set top ranked pharmacy search radius to 15mi

---

apps/app/src/views/components/SplitLayout.tsx
apps/app/src/views/routes/Settings/views/TreatmentTab.tsx

as per [this](https://www.notion.so/photons/Update-templates-catalog-layout-d7b8c3feb46e49148bf2a4eb422cc121) ticket, there are some spacing issues in the catalogs section.
the overflow issue has been resolved by switching from `vw` units to `100%`. `vw` will always be the view width, which sometimes can be too big - we instead want it to fill the parent container, which is what changing to `100%` does.
additionally, there was some annoying vertical discrepancy between the split contents due to differences in handling the first child vs the second. i've standardized it so they both have the same amount of margin.
**issues:** 
1. the vertical alignment of the table and the `add treatment` section on the right
2. the overflow of the table
**solutions:** 
1. the alignment of the table and …

fixing spacing in the treatments tab

---

packages/settings/src/lib/photon.ts

Removing amazon pharmacy as a mail order option for sesame within the patient app since we concluded our test.

Disable Amazon Pharmacy test

---

packages/elements/package.json
packages/elements/src/photon-medication-search/photon-medication-search-component.tsx

Search can tend to take a bit when you're only searching for "s". Limiting to 3 or more worked well for our prototypes. Responses are about to get larger with us returning generic as well when searching branded.

Limit med search to 3 or more chars in search string

---

.eslintignore
.github/workflows/prettier.yml
.gitignore
.prettierignore
apps/patient/codegen.ts
apps/patient/package.json
apps/patient/project.json
apps/patient/src/api/internal.ts
apps/patient/src/components/HorizontalStatusStepper.tsx
apps/patient/src/components/PharmacyInfo.tsx
apps/patient/src/components/ReadyText.tsx
apps/patient/src/components/StatusStepper.tsx
apps/patient/src/configs/graphqlClient.ts
apps/patient/src/data/demoOrder.ts
apps/patient/src/data/demoPharmacies.ts
apps/patient/src/graphql/queries.ts
apps/patient/src/utils/general.ts
apps/patient/src/utils/models.ts
apps/patient/src/utils/text.tsx
apps/patient/src/views/Main.tsx
apps/patient/src/views/Pharmacy.tsx
apps/patient/src/views/Status.tsx
package-lock.json
package.json

Add codegen to the patient app.
- We're always using `patient-api` for the patient app so its easy to point at
- The codegen will hot-reload if you run `npm run patient` but you can also run `nx run patient:codegen:watch` (or just `nx run patient:codegen` if you don't want to watch
- For now, this keeps the `graphql-request` library as the client. This provides no caching or anything, so we should eventually revisit that
- We currently co-locate all our queries and mutations. This makes some stuff easy (i.e. the types are consistent across pages) but other stuff hard. For a simple app like the patient app, I think the current approach is fine. But as the app gets more complex we might want to move to Apollo or Relay
- By generating our own types, this PR also removes the dependency on the …

codegen the patient app

---

packages/elements/src/photon-multirx-form/photon-prescribe-workflow.tsx

Next se'll need to be able to turn on whole orgs and not just individual users

Allow adding whole organizations to the new medication search

---

apps/patient/src/views/Pharmacy.tsx

Toggle was getting unset if the price list pharmacies came back empty, so waiting until the pharmacy fetch finishes before triggering the action.

Fix Cash price displayed datadog action

---

packages/elements/package.json
packages/elements/src/photon-medication-search/photon-medication-search-component.tsx
packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
packages/elements/src/photon-multirx-form/photon-prescribe-workflow-component.tsx
packages/elements/src/photon-multirx-form/photon-prescribe-workflow.tsx
packages/elements/src/stores/catalog.ts

Two additional params are added:
`catalog-id`
This allows constraining a caller to a specific catalog
`allow-off-catalog-search`
This gives control to allowing or blocking searching for items _not_ on the catalog
These will be used in mail order configurations, so a customer can programmatically constrain the meds allowed to be prescribed.

Add catalog params to photon-prescribe-workflow

---

apps/patient/src/components/Coupons.tsx
apps/patient/src/views/Pharmacy.tsx

- restrict frontend to only show 1 coupon - saw one order with this, i believe it was reroute to the same pharmacy
- hide toggle for multirx - backend was limiting this already by returning no pharmacies
- don't show prices for glp1 - this was an original requirement that i missed
- don't register `cash_price_displayed` action unless toggled to price search - need this change now that we're not defaulting to cash price search

Discount card test follow-up

---

packages/elements/package.json
packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx

When the draft is added to the order, we will emit the event `photon-draft-prescription-created` with the draft prescription information.

Add Event when adding a Draft Prescription

---

package-lock.json
packages/components/src/systems/DraftPrescriptions/index.tsx
packages/elements/index.html
packages/elements/package.json
packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
packages/elements/src/photon-multirx-form/components/DraftPrescriptionCard.tsx
packages/elements/src/photon-multirx-form/photon-prescribe-workflow.tsx

https://www.notion.so/photons/Confusing-language-when-send-order-is-false-11f8bfbbf4ec80e1ba73cf8771b01abe?pvs=4

Setting "Enable Order" to false has bad copy

---

apps/app/src/views/components/Auth.tsx
apps/app/src/views/routes/Login.tsx
apps/app/src/views/routes/Main.tsx
packages/react/src/provider.tsx
packages/sdk/src/auth.ts

for this ticket: https://www.notion.so/photons/URL-params-not-persisted-on-redirect-1288bfbbf4ec8055b43bf981aa95df6e
session expires while url contains search params: user gets returned to url with search params after logging back in
user goes to the login page: user is direct to `/prescriptions` after login
user is logged out and tries to access url with search params: user is directed to that url with search params after login
session expires while patient is at `/patients`: user is returned to `/patients` after logging back in

persist url search params when session expires

---

apps/patient/src/components/PharmacyCard.tsx
apps/patient/src/components/PharmacyInfo.tsx
apps/patient/src/components/PickupOptions.tsx
apps/patient/src/views/Pharmacy.tsx

[Eng ticket](https://www.notion.so/photons/Disallow-rerouting-to-the-same-pharmacy-892bce0804624bf8a33d50627d4fe7d1)
Allowing routing to the same pharmacy creates unnecessary ops costs, this disables that.
Example:

Disallow routing to the same pharmacy

---

apps/patient/src/components/PharmacyInfo.tsx
apps/patient/src/utils/general.ts
apps/patient/src/views/Pharmacy.tsx
apps/patient/src/views/StatusV2.tsx

We currently don't have any default behavior for mail order pharmacies that don't have any information in the `PHARMACY_BRANDING` constant.

Display default info for mail order pharmacy, move tracking link into the pharmcy info section

---

packages/elements/index.html
packages/elements/package.json
packages/elements/src/photon-multirx-form/photon-prescribe-workflow.tsx

[Example situation](https://app.datadoghq.com/logs?query=env%3Aphoton%20-%40identity.claims.http%5C%3A%2F%2Fphoton.health%2Forg_id%3Aorg_Oxc0CSPfdiyWW3VM%20source%3Alambda%20-service%3A%28events%20OR%20admin%20OR%20state-machine-executors%29%20functionname%3A%28create_prescriptions%20OR%20get_patient%29&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice%2Cfunctionname&fromUser=true&graphType=flamegraph&messageDisplay=inline&refresh_mode=paused&sort=time&storage=hot&stream_sort=desc&viz=stream&from_ts=1733818056335&to_ts=1733818058552&live=false) showing that there is a second difference between the get_patient request and the create_order request.
This resulted in the cached patient from a previous order being erroneously set to the new order.

Fix Race Condition between getting a patient and creating an order

---

packages/components/src/systems/RecentOrders/RecentOrders.tsx
packages/components/src/systems/RecentOrders/RecentOrdersDuplicateDialog.tsx

[Ref this ticket](https://www.notion.so/photons/Investigate-Duplicate-Orders-Potentially-Update-Logic-1528bfbbf4ec80b69129ea041681e9f6?pvs=4)
I’ve confirmed that the duplicate modal is displaying between different providers with the same organization.
My thinking is to add the provider name and date to the modal to make it very clear that it was prescribed perhaps by someone else and when.
Before:
After:

Add provider and date to duplicate order modal

---

packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx

Fix Dosing Calculator Alignment in Add Prescription Card

---

packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx

ticket for reference: [Prevent prescribe from adding the same medication twice to the same order](https://www.notion.so/photons/Prevent-prescribe-from-adding-the-same-medication-twice-to-the-same-order-1588bfbbf4ec801498e7eda0c2d81b50)

add an error toast if draft prescription already exists in order

---

packages/elements/index.html
packages/elements/package.json
packages/elements/src/photon-multirx-form/components/PatientCard.tsx
packages/elements/src/photon-multirx-form/photon-prescribe-workflow.tsx

https://photonhealth.slack.com/archives/C03TRQ4NLE5/p1739919711496799
Stale customer data can be sent in orders while the new patient information is being fetched. Previous attempts [here](https://github.com/Photon-Health/client/pull/1518/files) and here with [the action reset](https://github.com/Photon-Health/client/pull/1528/files).
This also seems to fix an issue we've been seeing[ in our data](https://www.notion.so/photons/We-get-warnings-Fill-s-for-one-or-more-prescriptions-do-not-belong-to-patient-pat_-provided-on-t-19f8bfbbf4ec80aabdcceb79e69238d3?pvs=4):

Fix stale patient data being sent with new orders

---

apps/patient/src/views/Pharmacy.tsx

people who should have the experiment active are not seeing amazon as an option, i suspect this is why

showing branded options if `amazonPharmacyEndOfPharmacyTestSegment` experiment is active

---

README.md
apps/app/README.md
packages/components/.storybook/main.js
packages/components/README.md
packages/components/dev/App.tsx
packages/components/src/index.ts
packages/components/src/systems/PatientMedHistory/PatientMedHistoryTable.stories.tsx
packages/components/src/systems/PatientMedHistory/PatientMedHistoryTable.tsx
packages/components/src/systems/PatientMedHistory/index.tsx
packages/components/src/utils/formatPrescriptionDetail.test.ts
packages/components/src/utils/formatPrescriptionDetail.ts
packages/components/src/utils/storybookUtils.ts
packages/components/tsconfig.json
packages/elements/README.md
packages/elements/package.json

* MedHistory shows a line of text with prescription data:
* quantity
* days supply
* refills remaining
* instruction (i.e. "sig")
* toggle button allows expansion. 
* need this because there isn't a lot of space to show all the prescription details, especially the longer instructions field
* Improve READMEs for local development
* main README links to sub-READMEs
* replaced broken `npm start` commands with `npx nx` commands
Prescriptions with the same medication.treatment expand/collapse together (see end of demo video). Not sure if this actually happens outside test data environment or if it needs to be fixed.
https://github.com/user-attachments/assets/10d9f903-6f84-4975-81eb-0a03651fae1b
related milestone: https://www.notion.so/photons/Med-History-Details-in-Embedded-Flow-1908bfbbf4ec80b …

PatientMedHistory shows prescription details

---

apps/app/src/views/routes/Settings/components/client-credentials/SPAClientEditForm.tsx

We need to enable customers to use wildcards in the subdomain of the URLs that they're whitelisting
https://github.com/user-attachments/assets/a47451d5-8eb1-4186-b999-6d432a85d732
https://github.com/user-attachments/assets/96aa9b70-4350-4c62-864a-39baaf8d2729

Allow wildcards in the subdomain of whitelisted ulrs, validation fix

---

apps/app/src/views/routes/PrescriptionForm.tsx
packages/components/dev/App.tsx
packages/components/src/particles/Card/index.tsx
packages/components/src/particles/FlyoutMenu/FlyoutMenu.stories.tsx
packages/components/src/particles/FlyoutMenu/FlyoutMenu.tsx
packages/components/src/particles/FlyoutMenu/index.ts
packages/components/src/particles/IconButton/index.tsx
packages/components/src/systems/DraftPrescriptions/index.tsx
packages/components/src/systems/PatientMedHistory/PatientMedHistoryTable.stories.tsx
packages/components/src/systems/PatientMedHistory/PatientMedHistoryTable.tsx
packages/components/src/systems/PatientMedHistory/index.tsx
packages/elements/README.md
packages/elements/index.html
packages/elements/package.json
packages/elements/src/photon-med-history/photon-med-history.tsx
packages/elements/src/photon-multirx-form-wrapper/photon-multirx-form-wrapper-component.tsx
packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
packages/elements/src/photon-multirx-form/components/DraftPrescriptionCard.tsx
packages/elements/src/photon-multirx-form/components/PatientCard.tsx
packages/elements/src/photon-multirx-form/photon-prescribe-workflow-component.tsx
packages/elements/src/photon-multirx-form/photon-prescribe-workflow.tsx

Added FlyoutMenu, but ended up not using it. Left it in for potential future use.
https://github.com/user-attachments/assets/00924392-f516-4c68-a713-230b0d9833e2
https://github.com/user-attachments/assets/67751d6c-7b87-47b9-be32-b7e5094e5af5

Add 1 click refill button to med history

---

.github/workflows/lint.yml

Sometimes Node is already installed/cached on the agents so we need to clear the cache when linting.
This should fix cache issues such as this:
```
Run npm ci
npm error code EEXIST
npm error syscall rename
npm error path /home/runner/.npm/_cacache/tmp/9f8c2973
npm error dest /home/runner/.npm/_cacache/content-v2/sha512/00/0d/d3563fb40368ae2284245842bfb6a16306ada3fba3cee98d3325cbf32c016110520edc72f4be5b3d8562e77196c001b2b499aafba19e15d3bf48fea3ccc6
npm error errno -2
npm error ENOENT: no such file or directory, rename '/home/runner/.npm/_cacache/tmp/9f8c2973' -> '/home/runner/.npm/_cacache/content-v2/sha512/00/0d/d3563fb40368ae2284245842bfb6a16306ada3fba3cee98d3325cbf32c016110520edc72f4be5b3d8562e77196c001b2b499aafba19e15d3bf48fea3ccc6'
npm error File exists: …
```

Fix errors when agent has cached node packages

---

apps/app/src/views/routes/PrescriptionForm.tsx
packages/components/src/particles/Dialog/index.tsx
packages/components/src/systems/DraftPrescriptions/index.tsx
packages/components/src/systems/PatientMedHistory/PatientMedHistoryTable.stories.tsx
packages/components/src/systems/PatientMedHistory/PatientMedHistoryTable.tsx
packages/components/src/systems/PatientMedHistory/index.tsx
packages/components/src/systems/RecentOrders/RecentOrders.tsx
packages/components/src/utils/storybookUtils.ts
packages/components/types/zendesk.d.ts
packages/elements/package.json
packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
packages/elements/src/photon-multirx-form/components/DraftPrescriptionCard.tsx
packages/elements/src/photon-multirx-form/components/PatientCard.tsx
packages/elements/src/photon-multirx-form/photon-prescribe-workflow.tsx
packages/elements/src/photon-multirx-form/util/repopulateForm.ts

* Rework how refill is added to form state. No longer managing separate `prescriptionIds` signal-state
* Empty history shows "No medication history found" message
* Remove toggle button - medication name/details are always expanded
* Fix z-index conflicts between IconButtons, sticky grid header, and dialog popups
* Fix clicking items with the same Treatment ID (e.g. 2+ prescriptions of "amoxicillin 500mg") expanding all rows with that Treatment ID
* Fix refill being clickable while orders are loading/reloading
* Refactors
*  type mappings, prop naming, code organization
* Remove unused `active` and `comment` fields

Enable med history refill button

---

packages/elements/src/photon-multirx-form/photon-prescribe-workflow.tsx

* In embed flow, after editing a prescription, we want the prescription form to auto close.
* In clinical app flow, the form is currently always open, and this PR shouldn't affect that.
* One exception: clicking "Renew" button from prescription details page will navigate to the prescription form page with the form closed by default.
[Notion issue ticket](https://www.notion.so/photons/Collapse-prescriber-form-after-a-template-edit-1cb8bfbbf4ec80aab2c9c4da030a328d?pvs=4)

Close rx form after editing

---

.gitignore
apps/patient/src/views/Pharmacy.tsx
packages/settings/src/lib/neutron.ts
packages/settings/src/lib/photon.ts

To show the price toggle for sesame, off by default, and surface prices once again from rxsense.

Enable pricing for sesame non-GLP1s

---

apps/app/src/views/routes/Settings/components/profile/ProfileEditForm.tsx

- Error message if the NPI is missing: "NPI is required for prescribers"
- Error message if the NPI is invalid: "Invalid NPI"
Question: Should the error message also include instructions on how to add/fix their NPI? If so, would we need to instruct the provider to reach out to someone?

show error message for missing or invalid NPI
