Photon-Health/client

- buildspec.yml
- package-lock.json
- packages/elements/package.json
- packages/elements/project.json
- packages/elements/src/photon-patient-dialog/index.tsx
- packages/elements/src/photon-patient-form/index.tsx
- packages/elements/src/photon-sex-input/index.tsx
- packages/elements/src/stores/form.ts
Sorry, not sorry, for crazy PR title. But this is my task ref https://www.notion.so/photons/Sex-is-not-required-on-frontend-when-it-is-required-for-the-API-15f46c740b254b93badcace18a18c33c?pvs=4
Found other fields that were not being validated on patient create form including first name, last name, phone, and email.
> Sex is required

- apps/app/src/App.tsx
- apps/app/src/views/routes/Playground.css
- apps/app/src/views/routes/Playground.tsx
- package-lock.json
- package.json
removed because this issue was blocking monorepo https://github.com/graphql/graphiql/issues/2997, but now it's resolved
> Re add playground

- apps/app/src/App.tsx
- apps/app/src/views/routes/PatientForm.tsx
- apps/app/src/views/routes/Playground.css
- apps/app/src/views/routes/Playground.tsx
- apps/app/src/views/routes/UpdatePatientForm.tsx
- package-lock.json
- package.json
- packages/elements/src/photon-multirx-form-wrapper/index.tsx
- patient list loads correctly
- playground back up
- new patient form is cleared
> Empty patient list

- packages/elements/package.json
- packages/elements/src/photon-authorized/index.tsx
- packages/elements/src/photon-multirx-form/index.tsx
- packages/elements/src/photon-patient-form/index.tsx
- packages/elements/src/store.ts
- creates an `isAuthorized` value in store that checks if sdk org matches user org
- adds a `PhotonAuthorized` wrapper that displays children based on `isAuthorized` value
cc @samkotlove @cawfeecoder
> Check for Org id match to authorize

- packages/elements/src/photon-authorized/index.tsx
Task Ref https://www.notion.so/photons/Not-Signed-In-Error-441c4b553fbd42c2949da98ba0e8ce97?pvs=4
> don't show unless done loading

- apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/index.tsx
It'll likely be a few days till we're ready to surface send to patient on photon
> Hide send to patient on photon

- apps/app/src/views/routes/Order.tsx
> Fix missing tag text without order fulfillment

- apps/app/src/views/routes/NewOrder/components/OrderForm.tsx
Missed the conditional that used to wrap the preferred pharmacies check
> Fix id error on new order

- packages/elements/src/photon-button/index.tsx
- packages/elements/src/photon-multirx-form-wrapper/index.tsx
- packages/elements/src/photon-patient-dialog/index.tsx
- packages/elements/src/photon-phone-input/index.tsx
- packages/elements/src/store.ts
I'm taking out unrelated updates from the sentry PR https://github.com/Photon-Health/client/pull/62
- fix button spinners in the forms, should only spin on the button you clicked on
- phone input was throwing unhandled errors when the numbers were too short
- wrap checksession in try catch
> fix button spinner, phone input errors, check session errors

- packages/elements/src/photon-datepicker/formatDate.ts
- packages/elements/src/photon-datepicker/index.tsx
This will take a paste in the format of mm dd yyyy and paste it correctly into the datepicker
```
formatDate('4/2/2022') // '2022-04-02'
formatDate('4 2 2022') // '2022-04-02'
formatDate('04 02 2022') // '2022-04-02'
formatDate('4-2-2022') // '2022-04-02'
formatDate('aoeu') // ''
formatDate('2022') // ''
formatDate('') // ''
```
> parse the paste

- packages/elements/src/photon-datepicker/index.tsx
- packages/elements/src/photon-phone-input/index.tsx
- fixes Edit patient DOB, was showing today's date
- BONUS, fixes typing issue with phone input... first digit wasn't getting registered 🤷‍♀️
> Edit Patient DOB working 

- packages/elements/src/photon-multirx-form/components/DraftPrescriptionCard.tsx
> Long Patient Instructions break Pending Prescriptions

- apps/app/src/utils.ts
- apps/app/src/views/routes/PatientForm.tsx
- apps/app/src/views/routes/UpdatePatientForm.tsx
- packages/elements/src/photon-multirx-form/index.tsx
- packages/elements/src/photon-patient-form/index.tsx
- packages/elements/src/stores/form.ts
- fix `formatDateLong` to read as UTC, DOB was behind a day on the patient page
- should clear form when creating new patient after editing other patients
- fix edit patient inside of app getting wrong DOB, but only on internal navigation 🤷‍♀️
> Patient DOB messed up in other places

- apps/app/src/utils.ts
- apps/app/src/views/components/TablePage.tsx
- apps/app/src/views/routes/NewOrder/components/OrderForm.tsx
- apps/app/src/views/routes/NewOrder/components/PatientAddressCard.tsx
- apps/app/src/views/routes/PatientForm.tsx
- apps/app/src/views/routes/Prescriptions.tsx
- apps/app/src/views/routes/UpdatePatientForm.tsx
- packages/elements/src/photon-datepicker/index.tsx
- packages/elements/src/photon-multirx-form/components/DraftPrescriptionCard.tsx
- packages/elements/src/photon-patient-form/index.tsx
- packages/elements/src/photon-phone-input/index.tsx
- packages/elements/src/stores/form.ts
- ability to filter by prescription status in App (for peachy)
- ability to save patient’s address from the new order form
- fix edit Patient DOB
- fix phone input not capturing first keystroke
- fix visual issue with pending prescriptions
- app was displaying the wrong DOB on the patient page, it was a day behind because of a UTC error
- Fixed some lingering pre-populated forms when switching between editing and creating patients in app
> Feat update neutron small bugs

- apps/app/src/utils.ts
- apps/app/src/views/components/TablePage.tsx
- apps/app/src/views/routes/NewOrder/components/OrderForm.tsx
- apps/app/src/views/routes/NewOrder/components/PatientAddressCard.tsx
- apps/app/src/views/routes/PatientForm.tsx
- apps/app/src/views/routes/Prescriptions.tsx
- apps/app/src/views/routes/UpdatePatientForm.tsx
- packages/elements/src/photon-datepicker/index.tsx
- packages/elements/src/photon-multirx-form/components/DraftPrescriptionCard.tsx
- packages/elements/src/photon-patient-form/index.tsx
- packages/elements/src/photon-phone-input/index.tsx
- packages/elements/src/stores/form.ts
- ability to filter by prescription status in App (for peachy)
- ability to save patient’s address from the new order form
- fix edit Patient DOB
- fix phone input not capturing first keystroke
- fix visual issue with pending prescriptions
- app was displaying the wrong DOB on the patient page, it was a day behind because of a UTC error
- Fixed some lingering pre-populated forms when switching between editing and creating patients in app
> Feat update photon small bugs

- packages/elements/src/photon-dispense-units/index.tsx
- packages/elements/src/photon-dosage-calculator/components/DosageUnitsDropdown.tsx
- packages/elements/src/photon-dosage-calculator/components/LiquidDosageUnitsDropdown.tsx
- packages/elements/src/photon-dosage-calculator/components/VolumeUnitsDropdown.tsx
- packages/elements/src/photon-dosage-calculator/components/WeightUnitsDropdown.tsx
- packages/elements/src/photon-gender-input/index.tsx
- packages/elements/src/photon-med-search/components/MedicationNameDropdown.tsx
- packages/elements/src/photon-med-search/components/MedicationRouteDropdown.tsx
- packages/elements/src/photon-med-search/components/MedicationStrengthDropdown.tsx
- packages/elements/src/photon-patient-select/index.tsx
- packages/elements/src/photon-pharmacy-search/index.tsx
- packages/elements/src/photon-prescription-select/index.tsx
- packages/elements/src/photon-sex-input/index.tsx
- packages/elements/src/photon-state-input/index.tsx
- `null is not an object (evaluating 'e.name')` [REF](https://photon-health.sentry.io/issues/4009988885/?project=6641717&referrer=slack)
> Various Sentry Errors

- apps/patient/src/views/Review.tsx
Nuthin' pr to test both apps are building correctly. We don't have any smart logic to detect changes in one or both apps yet so ideally it should build both.
> Test builds

- apps/app/src/configs/logout.boson.ts
- apps/app/src/configs/logout.neutron.ts
- apps/app/src/configs/logout.photon.ts
- apps/app/src/models/general.ts
- apps/app/src/views/components/Auth.tsx
- packages/react/src/provider.tsx
- packages/sdk/src/auth.ts
ref https://auth0.com/docs/api/authentication#logout
setting federated logout specifically for peachy for now.
> Federated Logout

- apps/app/src/views/routes/Patient.tsx
- apps/app/src/views/routes/Patients.tsx
This doesn't fix the fact that search is returning null in patients array. Also, going to a patient's page will just kick you back to `/patients` route
ref #111
> Cosmetic Fix, Invalid patient phone number crashes app

- packages/elements/package.json
- packages/elements/src/photon-patient-dialog/index.tsx
- packages/elements/src/photon-patient-form/index.tsx
> Element: Fix New Patient Validation 

- apps/patient/package.json
- apps/patient/src/components/PharmacyCard.tsx
- apps/patient/src/components/PharmacyList.tsx
- apps/patient/src/components/Rating.tsx
- apps/patient/src/utils/models.ts
- apps/patient/src/views/Pharmacy.tsx
- package-lock.json
- package.json
Added:
- google ratings
- google hours (closes, opens, open now, permanent/temporary close, lunch window, 24hr)
- better error handling on multiple queries
Tested:
- Locations all across the US (portland, chicago, arizona, new york, new jersey, miami, alabama, south dakota, colorado)
- Slow 3G
- Hitting query limit
- Returning all pharmacies nearby
> feat(pharmacy selection): ratings and hours

- apps/patient/src/components/PharmacyCard.tsx
- apps/patient/src/utils/general.ts
- apps/patient/src/utils/models.ts
- apps/patient/src/views/Pharmacy.tsx
Changes
- Fix close time being incorrect if current time is after lunch window
- Add appended day prefix to next opening time (Mon, Tues, Wed)
> feat(pharmacy hours): next open day prefix, fix lunch window

- apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/index.tsx
> Also check `sendToPatientUsers` on enabling tab

- packages/elements/package.json
- packages/react/package.json
- packages/sdk/package.json
- packages/sdk/src/auth.ts
The Promise is returned immediately without waiting for it to resolve or reject, the catch block is not executed when the `getTokenSilently` error occurs.
> Catch getTokenSilently Error

- apps/app/src/configs/fulfillment.boson.ts
- apps/app/src/configs/fulfillment.neutron.ts
- apps/app/src/configs/fulfillment.photon.ts
- apps/app/src/views/routes/NewOrder/components/OrderForm.tsx
- apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/index.tsx
- turn on STP for moped org
- make STP first tab
- fix bug that arose due STP being first, essentially it was still using default pharm instead of STP
> Enable send to patient for all moped prescribers

- packages/elements/src/photon-treatment-select/index.tsx
> Error Reading ID

- package-lock.json
- packages/elements/src/photon-datepicker/index.tsx
- packages/elements/src/photon-patient-dialog/index.tsx
- packages/elements/src/photon-patient-form/index.tsx
- packages/elements/src/photon-treatment-select/index.tsx
- packages/elements/src/validators/index.ts
- patient datepicker can't be in future, initializes empty when creating patient
> Neutron: Patient Datepicker

- package-lock.json
- packages/elements/src/photon-datepicker/index.tsx
- packages/elements/src/photon-patient-dialog/index.tsx
- packages/elements/src/photon-patient-form/index.tsx
- packages/elements/src/photon-treatment-select/index.tsx
- packages/elements/src/validators/index.ts
- patient datepicker can't be in future, initializes empty when creating patient
> Photon: Patient Datepicker

- packages/elements/src/photon-datepicker/index.tsx
- packages/elements/src/photon-dropdown/index.tsx
- packages/elements/src/photon-number-input/index.tsx
- packages/elements/src/photon-patient-form/index.tsx
- packages/elements/src/photon-phone-input/index.tsx
- packages/elements/src/photon-text-input/index.tsx
- packages/elements/src/photon-textarea/index.tsx
before
after 
closes #168 
before
after 
closes #181
> Fix two form alignment issues

- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
- packages/elements/src/photon-number-input/index.tsx
If you select a medication rather than a treatment it should not automatically pass validation.
closes #172
> Prevent Prescription Quantity set to 1 

- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
- packages/elements/src/photon-number-input/index.tsx
- Selecting a medication (rather than a treatment) no longer automatically passes validation
> Neutron: New Prescription Default values

- apps/patient/src/views/Pharmacy.tsx
> Comments on navigate pharmacy search

- apps/app/src/views/routes/NewOrder/components/OrderForm.tsx
Race condition with loading patient causing an issue, so rolling back one commit from my previous PR. Everything still works as expected to validate addresses
> Fix Address not Collapsing

- apps/app/src/hooks/usePrevious.ts
- apps/app/src/views/routes/NewOrder/components/OrderForm.tsx
- apps/app/src/views/routes/NewOrder/components/PatientAddressCard.tsx
- packages/elements/src/photon-patient-form/index.tsx
- packages/elements/src/validators/index.ts
- Elements: fixes validation on the update / create so that incorrect zip codes don't get introduced
- zip codes use the format of either 12345 or 12345-1234
- App: the address form will open up and display the error if theres something blocking sending the order
> Feat update neutron order validate

- apps/patient/src/components/CourierOptions.tsx
- apps/patient/src/components/PharmacyCard.tsx
- apps/patient/src/components/PickupOptions.tsx
- apps/patient/src/utils/queries.ts
- apps/patient/src/utils/text.json
- apps/patient/src/views/Pharmacy.tsx
Changes:
- communicate speed using tagline from capsule site ("Free, same-day prescription delivery")
- show patient delivery address
- initialize pharmacy options using patient address
- give card content a little breathing room
Example:
_Just for display purposes, Capsule isn't available in brooklyn yet_
https://user-images.githubusercontent.com/3934326/231016205-ee9ec555-d4d6-450e-81ac-74cbb001d7ec.mov
> Miscellaneous courier polishing

- apps/patient/src/views/Pharmacy.tsx
Just missed that I had re-added this again for checking UI
> Fix courier option always enabled

- apps/patient/src/components/CourierOptions.tsx
- apps/patient/src/components/PharmacyCard.tsx
- apps/patient/src/components/PickupOptions.tsx
- apps/patient/src/utils/queries.ts
- apps/patient/src/utils/text.json
- apps/patient/src/views/Pharmacy.tsx
This reverts commit 33c72cf703ad6ee3d1f7165af3bf77c0e53a8b47, reversing changes made to 5e81fd0ea1e11fbc3be0ed5d916c8ec8ce151d6d.
This only removes changes to client app to show patient address
> Revert "Miscellaneous courier polishing (#210)"

- package-lock.json
- packages/components/package.json
- packages/components/src/App.tsx
- packages/components/src/index.css
- packages/components/src/particles/Button/Button.stories.tsx
- packages/components/src/particles/Button/index.tsx
- packages/components/src/particles/ComboBox/index.tsx
- packages/components/src/particles/Dialog/Dialog.stories.tsx
- packages/components/src/particles/Dialog/index.tsx
- packages/components/src/particles/Icon/Icon.stories.tsx
- packages/components/src/particles/Icon/index.tsx
- packages/components/src/particles/Input/index.tsx
- packages/components/src/stores/pharmacy.ts
- packages/components/src/systems/LocationSelect/index.tsx
- packages/components/src/systems/PharmacySearch/index.tsx
- packages/components/src/systems/SelectLocation/index.tsx
- packages/components/src/utils/createTransition.ts
- packages/components/src/utils/getNavigatorLocation.ts
- packages/components/src/utils/loadGoogleScript.ts
Particles w/ storybook
- Icon
- Dialog
https://user-images.githubusercontent.com/700617/232055416-ddf9c706-9e65-477f-ba43-7434a84e0133.mov
System 
- SelectLocation based on modal in post prescribe
https://user-images.githubusercontent.com/700617/232053731-56cc3a18-8c96-43ed-8dd9-906a69b363a6.mov
ref #215
> Location Modal

- apps/app/src/views/components/TemplateView.tsx
> Easily copy template ID

- apps/app/src/views/routes/Order.tsx
- packages/sdk/src/fragments.ts
> Order Page's Fill Section has Link to prescription

- apps/app/src/views/routes/Order.tsx
- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
> Align Link List with Patient Page

- apps/app/src/App.tsx
- apps/app/src/views/components/TemplateView.tsx
- apps/app/src/views/routes/Order.tsx
- apps/app/src/views/routes/PrescriptionForm.tsx
- package-lock.json
- packages/components/package.json
- packages/components/src/App.tsx
- packages/components/src/index.css
- packages/components/src/particles/Button/Button.stories.tsx
- packages/components/src/particles/Button/index.tsx
- packages/components/src/particles/ComboBox/index.tsx
- packages/components/src/particles/Dialog/Dialog.stories.tsx
- packages/components/src/particles/Dialog/index.tsx
- packages/components/src/particles/Icon/Icon.stories.tsx
- packages/components/src/particles/Icon/index.tsx
- packages/components/src/particles/Input/index.tsx
- packages/components/src/stores/pharmacy.ts
- packages/components/src/systems/LocationSelect/index.tsx
- packages/components/src/systems/PharmacySearch/index.tsx
- packages/components/src/utils/createTransition.ts
- packages/components/src/utils/getNavigatorLocation.ts
- packages/components/src/utils/loadGoogleScript.ts
- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
- packages/sdk/src/fragments.ts
- align dose calculator button
- ability to copy template ids
- Fill on order page has link to prescription
- template ids in new prescription link
> Neutron: template ids in new prescription link

- apps/app/src/App.tsx
- apps/app/src/views/components/TemplateView.tsx
- apps/app/src/views/routes/Order.tsx
- apps/app/src/views/routes/PrescriptionForm.tsx
- package-lock.json
- packages/components/package.json
- packages/components/src/App.tsx
- packages/components/src/index.css
- packages/components/src/particles/Button/Button.stories.tsx
- packages/components/src/particles/Button/index.tsx
- packages/components/src/particles/ComboBox/index.tsx
- packages/components/src/particles/Dialog/Dialog.stories.tsx
- packages/components/src/particles/Dialog/index.tsx
- packages/components/src/particles/Icon/Icon.stories.tsx
- packages/components/src/particles/Icon/index.tsx
- packages/components/src/particles/Input/index.tsx
- packages/components/src/stores/pharmacy.ts
- packages/components/src/systems/LocationSelect/index.tsx
- packages/components/src/systems/PharmacySearch/index.tsx
- packages/components/src/utils/createTransition.ts
- packages/components/src/utils/getNavigatorLocation.ts
- packages/components/src/utils/loadGoogleScript.ts
- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
- packages/sdk/src/fragments.ts
- align dose calculator button
- ability to copy template ids
- Fill on order page has link to prescription
- template ids in new prescription link
> Photon: template ids in new prescription link

- apps/app/src/views/routes/PrescriptionForm.tsx
- packages/elements/package.json
- packages/elements/src/photon-treatment-select/index.tsx
https://photon-health.sentry.io/issues/4149391579/?project=6641717&referrer=slack
and patient-id not getting passed in app
> Error "e is not an Object"

- apps/app/src/views/routes/PrescriptionForm.tsx
- packages/elements/package.json
- packages/elements/src/photon-treatment-select/index.tsx
- fix sentry bug
- fix patientId query param
> Neutron hotfix 

- apps/app/src/views/components/NameView.tsx
- apps/app/src/views/components/Nav.tsx
- apps/app/src/views/components/PharmacyNameView.tsx
- apps/app/src/views/components/UserProfile.tsx
- packages/elements/package.json
- packages/elements/src/photon-med-search-dialog/index.tsx
- fixes r.at(0) is not a function
- fixes an issue when adding a medication to the catalog from the Advanced Medication Search Dialog, if you add it more than once it crashed
> Neutron: r.at nest

- apps/app/src/views/routes/Order.tsx
> Disable order cancel button in canceled state

- apps/app/src/views/routes/Orders.tsx
> Surface canceled state in orders table

- apps/patient/src/views/ReadyBy.tsx
- hide after hours when we're in after hours
- fix footer overlapping bottom options on small screens (iphone xs) when there is a selection
> Hide after hours during them

- apps/app/src/utils.ts
- apps/app/src/views/routes/Orders.tsx
> Flatten fill list on Orders Page

- apps/app/src/utils.ts
- apps/app/src/views/routes/Orders.tsx
- https://github.com/Photon-Health/client/pull/291
> Neutron: Fix Fills on Order Page

- apps/app/src/utils.ts
- apps/app/src/views/routes/Orders.tsx
- https://github.com/Photon-Health/client/pull/291
> Photon: Fix Fills on Order Page 

- apps/patient/src/components/StatusStepper/index.tsx
- apps/patient/src/utils/text.json
- apps/patient/src/views/Status.tsx
- packages/settings/src/lib/boson.ts
- packages/settings/src/lib/photon.ts
I faked mail order states for the amazon demo, now that we actually want to show mail order tracking, this uses the real ones
> Surface mail order statuses using actual states

- apps/patient/src/utils/queries.ts
> Support compound rx name on review page

- apps/app/src/views/routes/NewOrder/components/OrderForm.tsx
- apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/index.tsx
- nx.json
- packages/settings/src/index.ts
Closes #329 
https://github.com/Photon-Health/client/assets/3934326/22111a06-4c71-4e74-ada1-80423e65f11b
> Fix preferred pharmacy showing when fulfillment type not available

- apps/app/src/views/components/Auth.tsx
> Fix Login Redirect

- apps/app/src/views/components/Auth.tsx
- https://github.com/Photon-Health/client/issues/325
> Neutron: Fix Auth Redirect

- apps/app/src/views/components/Auth.tsx
- https://github.com/Photon-Health/client/issues/325
> Photon: Fix Auth Redirect

- packages/elements/src/photon-multirx-form/index.tsx
https://photon-health.sentry.io/issues/4206345755/?project=6641717
> Add Optional Chaining for conditional check

- apps/app/src/views/components/FillsSelect.tsx
https://photon-health.sentry.io/issues/4171455131/?project=6641717&referrer=slack
bigger question is why do some prescriptions not have patients
> Fix error reading "patient"

- packages/components/src/systems/DoseCalculator/DoseCalculator.test.tsx
- packages/components/src/systems/DoseCalculator/index.tsx
- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
From provider feedback https://www.notion.so/photons/Autofill-additional-DoseCalculator-values-3742b7a6a7f849b4a336682c9cc6e18f?pvs=4
> Dose Calculator AutoFill Days Supply

- apps/patient/src/utils/general.ts
- apps/patient/src/utils/models.ts
- apps/patient/src/utils/text.json
- apps/patient/src/views/ReadyBy.tsx
For test details [see here](https://www.notion.so/photons/Remove-ASAP-option-67a0fd490acd43eb8a8f224563709995)
> Remove asap ready-by option

- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
Tested on mobile with link from below, works.
> Decimal Erases Input on V1 Elements

- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
Waiting to test this on phone to see if it reverts decimal update I made (which came from this)
> Prescribe Not working if off catalog

- packages/react/package.json
- packages/sdk/package.json
- packages/sdk/src/lib.ts
- packages/sdk/src/utils.ts
- packages/settings/src/lib/photon.ts
- bump react
- bump sdk
- apollo cache-first
- piction health logo fix
- river health enable mail order
> Photon: Enable mail order for River Health

- apps/patient/src/views/ReadyBy.tsx
We were disabling the after hours option after 6pm but this doesn't really make sense in case it's 7pm and you do want it after hours. I'm not sure what the original idea behind this one was, so removing this limitation.
> Show after hours option at all times

- apps/app/src/views/routes/NewOrder/components/OrderForm.tsx
- apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/components/MailOrder.tsx
- apps/patient/src/views/ReadyBy.tsx
- App: fix mail order missing selection not blocking send order
- Patient: enable after hours option at all times
> Neutron: Mail order validation fix, after hours enabling

- apps/app/src/views/routes/NewOrder/components/OrderForm.tsx
- apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/components/MailOrder.tsx
- apps/patient/src/views/ReadyBy.tsx
- packages/settings/src/lib/neutron.ts
- fix mail order validation not blocking unselected pharmacy
- surface after hours at all times of day
- enable mail order for river on neutron
> Photon: Fix mail order validation not blocking unselected pharmacy

- apps/patient/src/components/BrandedOptions.tsx
- apps/patient/src/components/PickupOptions.tsx
- apps/patient/src/components/StatusStepper/index.tsx
- apps/patient/src/utils/general.ts
- apps/patient/src/utils/models.ts
- apps/patient/src/utils/text.json
- apps/patient/src/views/Pharmacy.tsx
- apps/patient/src/views/Status.tsx
- packages/settings/src/lib/boson.ts
- packages/settings/src/lib/neutron.ts
- packages/settings/src/lib/photon.ts
- Frontend prep for showing mail order status page for River Health
- Additional cleanup of fulfillment types
> Enable mail order statuses for River Health

- apps/patient/src/App.tsx
- apps/patient/src/utils/text.json
- apps/patient/src/views/Canceled.tsx
- apps/patient/src/views/Main.tsx
- apps/patient/src/views/NoMatch.tsx
- closes #383 
- fix /no-match unstyled
> Add patient order canceled ui

- packages/elements/package.json
- packages/elements/src/photon-treatment-select/index.tsx
> Neutron: Fix medication dropdowns for non-templates

- apps/patient/src/App.tsx
- apps/patient/src/views/Review.tsx
This is likely temporary so I am leaving the view itself. We'll consider re-adding a more permanent solution (store selections)  after the orders queue is stable and sortable
> Remove urgency options

- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
- packages/elements/src/photon-multirx-form/util/clearForm.ts
https://www.notion.so/photons/Clear-form-when-selecting-different-treatments-042a4537039f4e41aac74d53f43798e5?pvs=4
> Clear form when selecting different treatments

- packages/settings/src/lib/boson.ts
- packages/settings/src/lib/neutron.ts
> Update Newco brand color

- packages/components/src/systems/PharmacySelect/index.tsx
- packages/elements/package.json
- packages/settings/src/lib/boson.ts
- packages/settings/src/lib/neutron.ts
- Unset Pharmacy ID for "Send to Patient" Tab
- Update Newco brand color
> Neutron: Update Newco brand color

- apps/app/src/views/components/Page.tsx
- apps/app/src/views/components/PharmacyNameView.tsx
- apps/app/src/views/routes/Order.tsx
- apps/app/src/views/routes/Orders.tsx
In ROUTING we would show no state because we had no fulfillment state. This falls back to order states in the case of no fulfillment states.
> Better order states on order view

- apps/app/src/views/components/PharmacyNameView.tsx
- apps/app/src/views/routes/Order.tsx
- apps/app/src/views/routes/Orders.tsx
- packages/settings/src/lib/neutron.ts
- Better states on orders table
- Emily's test org
> Neutron: Better states on orders table

- apps/app/src/views/components/PharmacyNameView.tsx
- apps/app/src/views/routes/Order.tsx
- apps/app/src/views/routes/Orders.tsx
- packages/components/src/systems/PharmacySelect/index.tsx
- packages/elements/package.json
- packages/settings/src/lib/boson.ts
- packages/settings/src/lib/neutron.ts
App
- Better states on orders table
- Settings for Emily's test org
Elements
- [Pharmacy selector] Unset Pharmacy ID for "Send to Patient" Tab
Navigate
- Update NewCo branding settings
> Photon: Better states on orders table

- packages/settings/src/lib/photon.ts
Enable curexa orders for Xyon Health
> Photon: Xyon Health settings

- .github/workflows/npm-publish.yml
- package-lock.json
- package.json
@samkotlove would you mind adding `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to this repo's secrets? I tried creating a new one but don't have permission.
TODO
https://www.notion.so/photons/CDN-is-out-of-date-965c795386454f3f96e277db8d7f05bf?pvs=4
> Push Latest to CDN

- packages/components/src/index.ts
- packages/components/src/particles/RadioGroup/index.tsx
- packages/components/src/systems/PharmacySelect/MailOrderPharmacy.tsx
- packages/elements/src/photon-multirx-form/components/PharmacyCard.tsx
https://www.notion.so/photons/Improve-Selected-Pharmacy-Card-in-Elements-fcf57c07869744d596b6f469902306cd?pvs=4
FROM 
TO
> Improve Selected Pharmacy Card in Elements

- apps/patient/src/components/PharmacyCard.tsx
- apps/patient/src/components/PickupOptions.tsx
- apps/patient/src/utils/mutations.ts
- apps/patient/src/views/Pharmacy.tsx
This reverts commit 015c9413806b4f6056a4d7ded781570223d41749, reversing changes made to 71b86c28b522a428d79df0863f5e2d8953868dff.
> Revert "Add ability for patient to set preferred pharmacy (#437)"

- apps/patient/src/components/PharmacyCard.tsx
- apps/patient/src/components/PickupOptions.tsx
- apps/patient/src/utils/mutations.ts
- apps/patient/src/views/Pharmacy.tsx
This was already on neutron but we reverted to unblock template names because it's in lockstep with backend changes which were having trouble getting deployed
> Revive patient set preferred UI

- apps/app/src/views/routes/Settings/components/TemplateForm/index.tsx
- apps/patient/src/components/PharmacyCard.tsx
- apps/patient/src/components/PickupOptions.tsx
- apps/patient/src/utils/mutations.ts
- apps/patient/src/views/Pharmacy.tsx
- limit template names to 50 chars
- revive patient set preferred ui
> Neutron: Limit template names, set preferred ui

- apps/app/src/views/routes/Settings/components/TemplateForm/index.tsx
- apps/patient/src/components/PharmacyCard.tsx
- apps/patient/src/components/PickupOptions.tsx
- apps/patient/src/utils/mutations.ts
- apps/patient/src/views/Pharmacy.tsx
- packages/settings/src/lib/neutron.ts
DO NOT MERGE, WAITING ON SERVICES BACKEND
- patient set preferred
- limit template names to 50 chars
- enable mail order via carepoint for NewCo
> Photon: Allow patients to set preferred pharmacy

- apps/app/src/views/components/OrderStatusBadge.tsx
- apps/app/src/views/routes/Order.tsx
- apps/app/src/views/routes/Orders.tsx
- apps/app/src/views/routes/Patient.tsx
- apps/app/src/views/routes/Prescription.tsx
- packages/sdk/src/fragments.ts
- [Add Order table to page #448](https://github.com/Photon-Health/client/pull/448)
> Neutron: Add Order table to page

- apps/app/src/views/components/OrderStatusBadge.tsx
- apps/app/src/views/routes/Order.tsx
- apps/app/src/views/routes/Orders.tsx
- apps/app/src/views/routes/Patient.tsx
- apps/app/src/views/routes/Prescription.tsx
- packages/sdk/src/fragments.ts
- [Add Order table to page #448](https://github.com/Photon-Health/client/pull/448)
> Photon: Add Order table to page

- apps/app/src/views/routes/Order.tsx
https://photonhealth.slack.com/archives/C033T9N949M/p1689788405484219
> Revert Fulfillment Badge

- apps/app/src/views/routes/Order.tsx
- [Revert Fulfillment Badge #455](https://github.com/Photon-Health/client/pull/455)
> Neutron: revert order badges

- apps/app/src/views/routes/Order.tsx
- [Revert Fulfillment Badge #455](https://github.com/Photon-Health/client/pull/455)
> Photon: revert order badges

- packages/settings/src/lib/photon.ts
New org that's an offshoot of Xyon
> Add osei tutu

- apps/app/src/views/routes/Order.tsx
- apps/app/src/views/routes/Prescription.tsx
https://www.notion.so/photons/Site-crashes-if-you-try-to-go-to-an-order-from-a-different-organization-751a3b3ef4de4bb0b6a8c626d0b4007d?pvs=4
> Handle unknown Ids on Rx and Order Pages

- apps/app/src/views/components/Auth.tsx
- apps/app/src/views/components/CopyText.tsx
- apps/app/src/views/components/InfoGrid.tsx
- apps/app/src/views/components/Page.tsx
- apps/app/src/views/components/TablePage.tsx
- apps/app/src/views/routes/Order.tsx
- apps/app/src/views/routes/Orders.tsx
- apps/app/src/views/routes/Patient.tsx
- apps/app/src/views/routes/Patients.tsx
- apps/app/src/views/routes/Prescription.tsx
- apps/app/src/views/routes/Prescriptions.tsx
- apps/app/src/views/routes/Settings/components/Credentials.tsx
- apps/app/src/views/routes/Settings/index.tsx
- packages/elements/package.json
- packages/elements/src/photon-patient-form/index.tsx
- [Add Providers with Typeform #472](https://github.com/Photon-Health/client/pull/472)
- [Update Rx Hierarchy #469](https://github.com/Photon-Health/client/pull/469)
- [Update Patient Form to Say "Cell Phone Number" #463](https://github.com/Photon-Health/client/pull/463)
- [Perma loading #462](https://github.com/Photon-Health/client/pull/462)
- [Handle unknown Ids on Rx and Order Pages #474](https://github.com/Photon-Health/client/pull/474)
> Neutron: Add Providers

- apps/app/src/views/components/Auth.tsx
- apps/app/src/views/components/CopyText.tsx
- apps/app/src/views/components/InfoGrid.tsx
- apps/app/src/views/components/Page.tsx
- apps/app/src/views/components/TablePage.tsx
- apps/app/src/views/routes/Order.tsx
- apps/app/src/views/routes/Orders.tsx
- apps/app/src/views/routes/Patient.tsx
- apps/app/src/views/routes/Patients.tsx
- apps/app/src/views/routes/Prescription.tsx
- apps/app/src/views/routes/Prescriptions.tsx
- apps/app/src/views/routes/Settings/components/Credentials.tsx
- apps/app/src/views/routes/Settings/index.tsx
- packages/elements/package.json
- packages/elements/src/photon-patient-form/index.tsx
- [Add Providers with Typeform #472](https://github.com/Photon-Health/client/pull/472)
- [Update Rx Hierarchy #469](https://github.com/Photon-Health/client/pull/469)
- [Update Patient Form to Say "Cell Phone Number" #463](https://github.com/Photon-Health/client/pull/463)
- [Perma loading #462](https://github.com/Photon-Health/client/pull/462)
- [Handle unknown Ids on Rx and Order Pages #474](https://github.com/Photon-Health/client/pull/474)
> Photon: Add Providers

- apps/app/src/views/routes/Patient.tsx
- apps/app/src/views/routes/Settings/index.tsx
- apps/patient/src/components/PharmacyCard.tsx
- apps/patient/src/components/PickupOptions.tsx
- apps/patient/src/utils/models.ts
- apps/patient/src/views/Pharmacy.tsx
- packages/elements/package.json
- packages/elements/src/photon-patient-form/index.tsx
Add Provider Typeform Passes Environment Var (#477)
Cell Phone Number >>> Mobile Number (#476)
Feature indie pharmacies (#467)
> Neutron: Feature indie pharmacies

- apps/patient/src/views/Pharmacy.tsx
- decrease limit to 2 featured indie's
- fix indies showing up again in list
- fix fetched pharmacies after initial list showing w/o data
> Fix indie pharmacies bugs

- apps/patient/src/views/Pharmacy.tsx
Fix indie pharmacies bugs (#479)
> Neutron: Indie pharmacy fixes

- apps/app/src/views/routes/Patient.tsx
- apps/app/src/views/routes/Settings/index.tsx
- apps/patient/src/components/PharmacyCard.tsx
- apps/patient/src/components/PickupOptions.tsx
- apps/patient/src/utils/models.ts
- apps/patient/src/views/Pharmacy.tsx
- packages/elements/package.json
- packages/elements/src/photon-patient-form/index.tsx
- [Add Provider Typeform Passes Environment Var #477](https://github.com/Photon-Health/client/pull/477)
- [Cell Phone Number >>> Mobile Number #476](https://github.com/Photon-Health/client/pull/476)
- [Feature indie pharmacies #467](https://github.com/Photon-Health/client/pull/467)
- [Fix indie pharmacies bugs #479](https://github.com/Photon-Health/client/pull/479)
> Photon: Indie Pharm

- apps/app/src/index.tsx
- apps/patient/src/components/StatusStepper.tsx
- apps/patient/src/index.tsx
- apps/patient/src/views/Pharmacy.tsx
- apps/patient/src/views/Review.tsx
- apps/patient/src/views/Status.tsx
Mask any sensitive information from session replays
Learn about masking here: https://docs.datadoghq.com/real_user_monitoring/session_replay/privacy_options/
> Session replay masking

- apps/app/src/views/routes/Support.tsx
https://www.notion.so/photons/Fix-typos-on-Support-page-d972a7f40b9b42f7b3f09748391751d3?pvs=4
> Set up Settings Page

- apps/app/src/utils.ts
- apps/app/src/views/components/OrderStatusBadge.tsx
- apps/app/src/views/routes/Order.tsx
- apps/app/src/views/routes/Patient.tsx
- apps/app/src/views/routes/Prescription.tsx
- apps/app/src/views/routes/Support.tsx
- [1. ability to cancel order ](https://www.notion.so/photons/Add-ability-to-cancel-an-order-014f9cef17134624aa5124d2df84157a?pvs=4)
- [2. destructive actions to the bottom of page](https://www.notion.so/photons/Move-destructive-actions-to-bottom-of-Pages-3187cfaa37b048ec9ea94fdb7dc1b51d?pvs=4)
> Ability to cancel order

- apps/app/src/hooks/useIsIntersecting.ts
- apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/components/MailOrder.tsx
https://www.notion.so/photons/Default-Mail-Order-selection-656a7d448f2a435fb7ab7858ed7a2d42?pvs=4
> Select default mail order if there is only one

- apps/app/src/hooks/useIsIntersecting.ts
- apps/app/src/index.tsx
- apps/app/src/utils.ts
- apps/app/src/views/components/OrderStatusBadge.tsx
- apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/components/MailOrder.tsx
- apps/app/src/views/routes/Order.tsx
- apps/app/src/views/routes/Patient.tsx
- apps/app/src/views/routes/Prescription.tsx
- apps/app/src/views/routes/Support.tsx
- apps/patient/src/components/StatusStepper.tsx
- apps/patient/src/index.tsx
- apps/patient/src/views/Pharmacy.tsx
- apps/patient/src/views/Review.tsx
- apps/patient/src/views/Status.tsx
- [Ability to cancel order #483](https://github.com/Photon-Health/client/pull/483)
- [Session replay masking #484](https://github.com/Photon-Health/client/pull/484)
- [Set up Support Page #485](https://github.com/Photon-Health/client/pull/485)
- [Select default mail order if there is only one #486](https://github.com/Photon-Health/client/pull/486)
> Neutron: Cancel Order

- apps/app/src/views/routes/Prescription.tsx
- apps/app/src/views/routes/PrescriptionForm.tsx
- packages/elements/index.html
- packages/elements/package.json
- packages/elements/src/photon-multirx-form-wrapper/index.tsx
- packages/elements/src/photon-multirx-form/components/OrderCard.tsx
- packages/elements/src/photon-multirx-form/index.tsx
- packages/sdk/src/types.ts
https://www.notion.so/photons/Renew-Prescription-65236d222d9d44c4be3f56b8e0683ea6?pvs=4
(bonus)
https://www.notion.so/photons/Prescriptions-in-depleted-show-canceled-message-befa7a9fb43345f4b03fe04060830ea2?pvs=4
> Duplicate renew

- package-lock.json
- packages/elements/src/photon-form-wrapper/index.tsx
[Ticket](https://www.notion.so/photons/Center-popup-title-so-it-aligns-with-centered-content-be5513d984ae496cb04d19be1aa4b90f)
New:
> center form header

- apps/app/src/views/routes/Playground.css
- apps/app/src/views/routes/Playground.tsx
> Bigger Playground

- apps/app/src/views/components/LocationSearch.tsx
I wasn't able to recreate the issue but a few updates:
- Identified where it would be stalling out and logging any errors at that location
- putting `AutocompleteService` and `Geocoder` in a ref. this way on rerender it won't be creating new instances (maybe something there)
- removing a setTimeout on search, I'm not sure what it was there for, feels 1000ms snappier now (won't fix the problem)
https://www.notion.so/photons/Location-loading-indefinitely-1e2393b3282e4d1eb960fd3c8a582c59?pvs=4
> Location loading indefinitely

- apps/patient/src/views/Main.tsx
A bit of cleanup to split rendering logic from side effects
> Small Navigate cleanup

- packages/settings/src/lib/photon.ts
Not until backend update is live
> Patient Cannot Reroute

- packages/settings/src/lib/photon.ts
Patient can reroute? Patients CAN reroute.
> Photon: Enable patient reroutes

- apps/patient/src/components/PharmacyCard.tsx
- apps/patient/src/views/Status.tsx
Alert link and pharmacy links.
_removed the underline below_
> Fix link colors on status view

- apps/patient/src/components/PharmacyCard.tsx
- apps/patient/src/views/Status.tsx
- packages/components/dev/App.tsx
- packages/components/src/index.ts
- packages/components/src/particles/Text/index.tsx
- packages/components/src/systems/DraftPrescriptions/index.tsx
- packages/components/src/systems/DraftPrescriptions/utils/generateDraftPrescription.ts
- packages/elements/index.html
- packages/elements/package.json
- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
- packages/elements/src/photon-multirx-form/components/DraftPrescriptionCard.tsx
- packages/elements/src/photon-multirx-form/index.tsx
- packages/settings/src/lib/photon.ts
- [Draft Prescription Refactor #519](https://github.com/Photon-Health/client/pull/519)
- [Fix link colors on status view #520](https://github.com/Photon-Health/client/pull/520)
- [Scroll to top on status #521](https://github.com/Photon-Health/client/pull/521)
- [Patient can't reroute #523](https://github.com/Photon-Health/client/pull/523)
> Neutron: no patient reroute

- apps/app/src/views/routes/NewOrder/components/OrderForm.tsx
https://www.notion.so/photons/Warning-for-sending-order-doesn-t-make-sense-in-ROUTING-c6302e242160405f9a1b9b4779f07e59?pvs=4
> Show different warning on Order Creation if "Send to Patient"

- apps/app/src/utils.ts
> Set strings to UTC

- apps/app/declarations/dob-to-age.d.ts
- apps/app/src/mutations/index.ts
- apps/app/src/utils.ts
- apps/app/src/views/components/CopyText.tsx
- apps/app/src/views/components/InfoGrid.tsx
- apps/app/src/views/components/LocationSearch.tsx
- apps/app/src/views/components/NameView.tsx
- apps/app/src/views/components/SectionTitleRow.tsx
- apps/app/src/views/components/TemplateView.tsx
- apps/app/src/views/routes/NewOrder/components/OrderForm.tsx
- apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/components/LocalPickup.tsx
- apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/components/MailOrder.tsx
- apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/components/Pharmacy.tsx
- apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/components/SendToPatient.tsx
- apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/index.tsx
- apps/app/src/views/routes/Order.tsx
- apps/app/src/views/routes/Orders.tsx
- apps/app/src/views/routes/Patient.tsx
- apps/app/src/views/routes/Patients.tsx
- apps/app/src/views/routes/Prescription.tsx
- apps/app/src/views/routes/Prescriptions.tsx
- apps/app/tsconfig.json
- apps/patient/src/components/PharmacyCard.tsx
- packages/components/src/systems/PharmacySelect/PatientDetails.tsx
- packages/components/src/utils/formatAddress.ts
- packages/components/src/utils/toTitleCase.ts
- packages/elements/package.json
- packages/react/src/provider.tsx
- [Provider can Route Order #498](https://github.com/Photon-Health/client/pull/498)
- [Show different warning on Order Creation if "Send to Patient" #526](https://github.com/Photon-Health/client/pull/526)
- [Preferred Pharmacy in Send to Patient Card #522](https://github.com/Photon-Health/client/pull/522)
- [Set date strings to UTC #527](https://github.com/Photon-Health/client/pull/527)
- [Improved fetch times on list pages (rxs, orders, patients) #528](https://github.com/Photon-Health/client/pull/528)
> Neutron: Provider can route order

- apps/app/declarations/dob-to-age.d.ts
- apps/app/src/mutations/index.ts
- apps/app/src/utils.ts
- apps/app/src/views/components/CopyText.tsx
- apps/app/src/views/components/InfoGrid.tsx
- apps/app/src/views/components/LocationSearch.tsx
- apps/app/src/views/components/NameView.tsx
- apps/app/src/views/components/SectionTitleRow.tsx
- apps/app/src/views/components/TemplateView.tsx
- apps/app/src/views/routes/NewOrder/components/OrderForm.tsx
- apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/components/LocalPickup.tsx
- apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/components/MailOrder.tsx
- apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/components/Pharmacy.tsx
- apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/components/SendToPatient.tsx
- apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/index.tsx
- apps/app/src/views/routes/Order.tsx
- apps/app/src/views/routes/Orders.tsx
- apps/app/src/views/routes/Patient.tsx
- apps/app/src/views/routes/Patients.tsx
- apps/app/src/views/routes/Prescription.tsx
- apps/app/src/views/routes/Prescriptions.tsx
- apps/app/tsconfig.json
- apps/patient/src/components/PharmacyCard.tsx
- packages/components/src/systems/PharmacySelect/PatientDetails.tsx
- packages/components/src/utils/formatAddress.ts
- packages/components/src/utils/toTitleCase.ts
- packages/elements/package.json
- packages/react/src/provider.tsx
- [Provider can Route Order #498](https://github.com/Photon-Health/client/pull/498)
- [Show different warning on Order Creation if "Send to Patient" #526](https://github.com/Photon-Health/client/pull/526)
- [Preferred Pharmacy in Send to Patient Card #522](https://github.com/Photon-Health/client/pull/522)
- [Set date strings to UTC #527](https://github.com/Photon-Health/client/pull/527)
- [Improved fetch times on list pages (rxs, orders, patients) #528](https://github.com/Photon-Health/client/pull/528)
> Photon: Provider can route order

- apps/app/src/index.tsx
- apps/patient/src/index.tsx
- package-lock.json
- package.json
- update deprecated config
- enables heatmaps
> Bump datadog

- apps/app/src/App.tsx
- apps/app/src/views/routes/Settings/index.tsx
1. removes ability to set dark mode
2. unsets dark mode for users currently using it
https://www.notion.so/photons/Fix-dark-mode-922343c7bd454169b3a7f408773f4635?pvs=4
> Remove Dark Mode from Clinical App

- packages/components/src/index.ts
- packages/components/src/systems/DraftPrescriptions/index.tsx
- packages/elements/index.html
- packages/elements/package.json
- packages/elements/src/photon-multirx-form/components/DraftPrescriptionCard.tsx
- packages/elements/src/photon-multirx-form/index.tsx
ref https://www.notion.so/photons/Modify-template-defaults-in-elements-Ageless-b5cdf17394f241ed8bd544a86fa8bc87?pvs=4
> Override template defaults in elements

- apps/app/src/mutations/index.ts
- apps/app/src/views/components/GuardDialog.tsx
- apps/app/src/views/routes/Order.tsx
ref https://www.notion.so/photons/Provider-able-to-add-reason-for-cancelation-85020b64ddbb4d8ca919ae12da88446c?pvs=4
> Optionally get a reason for canceling from provider

- apps/app/src/App.tsx
- apps/app/src/index.tsx
- apps/app/src/mutations/index.ts
- apps/app/src/views/components/GuardDialog.tsx
- apps/app/src/views/routes/Order.tsx
- apps/app/src/views/routes/Settings/index.tsx
- apps/patient/src/index.tsx
- package-lock.json
- package.json
- packages/components/src/index.ts
- packages/components/src/systems/DraftPrescriptions/index.tsx
- packages/elements/index.html
- packages/elements/package.json
- packages/elements/src/photon-multirx-form/components/DraftPrescriptionCard.tsx
- packages/elements/src/photon-multirx-form/index.tsx
- #537 
- #536 (elements only)
- #535 
- #531
> Neutron: Provider reason for canceling orders

- apps/app/src/App.tsx
- apps/app/src/index.tsx
- apps/app/src/mutations/index.ts
- apps/app/src/views/components/GuardDialog.tsx
- apps/app/src/views/routes/Order.tsx
- apps/app/src/views/routes/Settings/index.tsx
- apps/patient/src/index.tsx
- package-lock.json
- package.json
- packages/components/src/index.ts
- packages/components/src/systems/DraftPrescriptions/index.tsx
- packages/elements/index.html
- packages/elements/package.json
- packages/elements/src/photon-multirx-form/components/DraftPrescriptionCard.tsx
- packages/elements/src/photon-multirx-form/index.tsx
- #537 
- #536 (elements only)
- #535 
- #531
> Photon: Provider reason for canceling orders

- apps/patient/src/views/Status.tsx
Hide option to set picked up til order received #540
> Neutron: Hide option to set picked up til order received

- apps/patient/src/views/Status.tsx
Hide option to set picked up til order received #540
> Photon: Hide option to set picked up til order received

- apps/app/src/views/routes/Prescription.tsx
- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
- packages/elements/src/photon-prescribe-form/index.tsx
ref https://www.notion.so/photons/Replace-Effective-Date-d8f016739c044acb9ad8985d6f30508b?pvs=4
> Effective Date => Do not fill before

- apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/components/MailOrder.tsx
- apps/app/src/views/routes/NewOrder/components/SelectPharmacyCard/components/Pharmacy.tsx
ref https://www.notion.so/photons/Hide-change-button-on-mail-order-if-there-s-only-one-24f8f8b446574d15bdd36a6176886d72?pvs=4
> Hide change button if there's one mail order pharm

- apps/app/src/views/components/MedicationSelect.tsx
not sure how this broke...
https://www.notion.so/photons/Dropdown-on-creating-template-is-not-selecting-from-the-catalog-554b8e377bd74d0ab7ad4e9065d060e6?pvs=4
> Fix Catalog Dropdown

- apps/patient/src/data/demoOrder.ts
- apps/patient/src/graphql/mutations.ts
- apps/patient/src/views/Pharmacy.tsx
- apps/patient/src/views/Review.tsx
- apps/patient/src/views/Status.tsx
- provider name -> patient name
- handle phone number via url param
> Stp demo follow-up

- apps/app/src/views/routes/PrescriptionForm.tsx
- packages/components/src/systems/DoseCalculator/index.tsx
- packages/elements/src/photon-multirx-form-wrapper/index.tsx
- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
- packages/elements/src/photon-multirx-form/index.tsx
- packages/elements/src/photon-multirx-form/util/clearForm.ts
url be like `http://localhost:3000/prescriptions/new?weight=100.5`
Will result in this:
Each new Rx draft will have reset to this note
https://www.notion.so/photons/Add-Weight-param-to-site-b2ae75c6e56e46fb94ba95bdb663542e?pvs=4
> Add weight to prescription

- apps/patient/src/components/Nav.tsx
- apps/patient/src/views/Main.tsx
- apps/patient/src/views/Status.tsx
- make try photon go to signup
- show demo modal on ready state
> More stp demo follow-up

- apps/patient/src/components/Nav.tsx
- apps/patient/src/views/Main.tsx
- apps/patient/src/views/Status.tsx
> Neutron: more stp demo follow-up

- package-lock.json
- package.json
- packages/components/dev/App.tsx
- packages/components/src/index.ts
- packages/components/src/particles/Text/index.tsx
- packages/components/src/systems/PatientInfo/index.tsx
- packages/elements/package.json
- packages/elements/src/photon-multirx-form/components/PatientCard.tsx
- packages/elements/src/photon-multirx-form/components/PharmacyCard.tsx
- packages/elements/src/photon-multirx-form/index.tsx
- packages/elements/src/photon-patient-dialog/index.tsx
https://www.notion.so/photons/Refactor-Patient-Card-In-Elements-5e60487183eb429ba2df4db5f20f654a?pvs=4
based on these wireframes, see all states below
https://www.notion.so/photons/Wireframe-updated-patient-card-aee505ca974549e181e4bc82ac225d93?pvs=4
> Patient card refactor

- package-lock.json
- package.json
- packages/components/dev/App.tsx
- packages/components/src/index.ts
- packages/components/src/particles/Text/index.tsx
- packages/components/src/systems/PatientInfo/index.tsx
- packages/elements/package.json
- packages/elements/src/photon-multirx-form/components/PatientCard.tsx
- packages/elements/src/photon-multirx-form/components/PharmacyCard.tsx
- packages/elements/src/photon-multirx-form/index.tsx
- packages/elements/src/photon-patient-dialog/index.tsx
- [Patient card refactor #576](https://github.com/Photon-Health/client/pull/576)
> Neutron: Refactor Patient Card

- apps/app/src/views/routes/PrescriptionForm.tsx
- package-lock.json
- packages/components/README.md
- packages/components/dev/App.tsx
- packages/components/src/index.ts
- packages/components/src/particles/Table/Table.stories.tsx
- packages/components/src/particles/Table/index.tsx
- packages/components/src/systems/PatientMedHistory/index.tsx
- packages/components/src/utils/formatDate.ts
- packages/components/src/utils/generateString.ts
- packages/elements/index.html
- packages/elements/package.json
- packages/elements/src/photon-med-search-dialog/index.tsx
- packages/elements/src/photon-med-search/components/MedicationConceptDropdown.tsx
- packages/elements/src/photon-med-search/index.tsx
- packages/elements/src/photon-multirx-form-wrapper/index.tsx
- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
- packages/elements/src/photon-multirx-form/components/PatientCard.tsx
- packages/elements/src/photon-multirx-form/index.tsx
- packages/sdk/src/lib.ts
- packages/sdk/src/utils.ts
- packages/settings/src/lib/boson.ts
- packages/settings/src/lib/neutron.ts
- packages/settings/src/lib/photon.ts
- packages/settings/src/types.ts
For:
- https://www.notion.so/photons/Add-Medical-History-panel-to-prescribe-view-e0a3dbb669734c5ba794055943825df7?pvs=4
- https://www.notion.so/photons/Add-ability-to-add-externally-reported-medical-history-for-a-patient-522000f490ba4a01b2512da4c7407262?pvs=4
✨ _video demo_
https://www.loom.com/share/b2f3c546b60b432798bfb3e6c22c8a5d
> Display and add to patient med history

- packages/components/src/particles/Table/index.tsx
- packages/components/src/systems/PatientInfo/index.tsx
- packages/components/src/systems/PatientMedHistory/index.tsx
- packages/elements/src/photon-card/index.tsx
- packages/elements/src/photon-radio-card/index.tsx
- N/A for empty fields
- Can the width of the name field be the max width of the text?
- Cursor for list item hover should be pointer
> Med History Fixes

- apps/app/src/views/routes/NewOrder/components/PatientCard.tsx
- packages/components/src/systems/PatientInfo/index.tsx
- packages/elements/src/photon-multirx-form/components/PatientCard.tsx
- Patient ID => Patient
- never hide patient card
https://photonhealth.slack.com/archives/C032PLRRMGC/p1695919594692989?thread_ts=1695749371.749979&cid=C032PLRRMGC
> Small Patient Card Updates

- apps/app/src/views/routes/NewOrder/components/PatientCard.tsx
- packages/components/src/systems/PatientInfo/index.tsx
- packages/elements/src/photon-multirx-form/components/PatientCard.tsx
> Neutron: Minor Patient Card update

- apps/app/src/views/routes/NewOrder/components/PatientCard.tsx
- packages/components/src/systems/PatientInfo/index.tsx
- packages/elements/src/photon-multirx-form/components/PatientCard.tsx
> Photon: Minor Patient Card Updates

- apps/app/src/views/routes/PrescriptionForm.tsx
- packages/components/src/systems/DoseCalculator/components/UnitSelect.tsx
- packages/components/src/systems/DoseCalculator/index.tsx
- packages/components/src/systems/PatientInfo/index.tsx
- packages/elements/src/photon-multirx-form-wrapper/index.tsx
- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
- packages/elements/src/photon-multirx-form/components/PatientCard.tsx
- packages/elements/src/photon-multirx-form/index.tsx
> Neutron: Weight Unit

- apps/app/src/views/routes/PrescriptionForm.tsx
- packages/components/src/systems/DoseCalculator/components/UnitSelect.tsx
- packages/components/src/systems/DoseCalculator/index.tsx
- packages/components/src/systems/PatientInfo/index.tsx
- packages/elements/src/photon-multirx-form-wrapper/index.tsx
- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
- packages/elements/src/photon-multirx-form/components/PatientCard.tsx
- packages/elements/src/photon-multirx-form/index.tsx
> Photon: Weight Unit

- apps/app/src/views/routes/Order.tsx
- apps/app/src/views/routes/Orders.tsx
ref https://www.notion.so/photons/Order-Page-has-blended-status-6912ebbd0e9843d795f523e3f117d0e4?pvs=4
> Blended Order State

- apps/app/src/views/components/Intercom.tsx
`app: "clinical" | "patient" | "pharmacy" | "website"`
> Flag intercom app type

- apps/app/src/views/components/Intercom.tsx
- apps/app/src/views/components/TablePage.tsx
- apps/app/src/views/routes/Order.tsx
- apps/app/src/views/routes/Orders.tsx
- apps/app/src/views/routes/Prescriptions.tsx
- packages/components/src/systems/PatientInfo/index.tsx
- #597 
- #596 
- #594 
- #592
> Neutron: Blended order and others

- apps/app/src/views/components/Intercom.tsx
- apps/app/src/views/components/TablePage.tsx
- apps/app/src/views/routes/Order.tsx
- apps/app/src/views/routes/Orders.tsx
- apps/app/src/views/routes/Prescriptions.tsx
- packages/components/src/systems/PatientInfo/index.tsx
- #597 
- #596 
- #594 
- #592
> Photon: Blended Order and others

- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
https://photonhealth.slack.com/archives/C05NXJ4KW2H/p1696971017751199
> Med Search Not Reopening

- package-lock.json
- package.json
- packages/elements/package.json
- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
> Neutron: Med Dialog Reopens

- package-lock.json
- package.json
- packages/elements/package.json
- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
> Photon: Med Dialog Reopens 

- apps/app/src/views/components/LocationSearch.tsx
One of our clinicians occasionally has trouble with google maps not loading. I can't recreate it so this does two things:
1. there's a chance that google maps api hasn't loaded yet, so this tries a few times to grab it, not just on component load
2. better sentry handling, I haven't seen any errors yet so that tells me it's not getting caught atm
> Capture Map Issues

- apps/app/src/views/routes/PrescriptionForm.tsx
- package-lock.json
- packages/components/src/particles/ComboBox/index.tsx
- packages/components/src/particles/Dialog/index.tsx
- packages/components/src/systems/LocationSelect/index.tsx
- packages/components/src/systems/PharmacySearch/index.tsx
- packages/components/src/systems/PharmacySelect/index.tsx
- packages/components/src/utils/autocompleteLocation.ts
- packages/components/src/utils/getLocations.ts
- packages/components/src/utils/loadGoogleScript.ts
- packages/elements/src/photon-multirx-form-wrapper/index.tsx
- packages/elements/src/photon-multirx-form/index.tsx
- packages/settings/src/lib/boson.ts
- packages/settings/src/lib/photon.ts
- packages/settings/src/types.ts
> Neutron: Combine Order and Rx For one provider

- packages/components/src/systems/PharmacySearch/index.tsx
- packages/components/src/systems/PharmacySelect/index.tsx
> Neutron: Fix Pharmacy Selection

- apps/app/src/views/routes/PrescriptionForm.tsx
- package-lock.json
- packages/components/src/particles/ComboBox/index.tsx
- packages/components/src/particles/Dialog/index.tsx
- packages/components/src/systems/LocationSelect/index.tsx
- packages/components/src/systems/PharmacySearch/index.tsx
- packages/components/src/systems/PharmacySelect/index.tsx
- packages/components/src/utils/autocompleteLocation.ts
- packages/components/src/utils/getLocations.ts
- packages/components/src/utils/loadGoogleScript.ts
- packages/elements/src/photon-multirx-form-wrapper/index.tsx
- packages/elements/src/photon-multirx-form/index.tsx
- packages/settings/src/lib/boson.ts
- packages/settings/src/lib/photon.ts
- packages/settings/src/types.ts
> Photon: Order and Rx combined

- packages/components/src/systems/LocationSelect/index.tsx
pressing enter here shouldn't select, you should select somethng in the dropdown instead
> Enter on Location Select shouldn't submit

- apps/app/src/utils.ts
- apps/app/src/views/components/NameView.tsx
- apps/app/src/views/routes/Orders.tsx
- apps/app/src/views/routes/Patients.tsx
- apps/app/src/views/routes/Prescriptions.tsx
Looks diff from image in notion, Sig under the Name
https://www.notion.so/photons/Add-Sig-to-Prescription-list-page-90553e1f56f9411c9638d3bb22af2a43?pvs=4
https://www.notion.so/photons/Update-Quantity-on-Prescriptions-list-page-c5f4f78d10e548228a23e6d469a7fd62?pvs=4
Also took away the name avatars
> Fixes rx list page

- packages/components/src/index.ts
- packages/components/src/particles/Spinner/Spinner.stories.tsx
- packages/components/src/particles/Spinner/index.tsx
- packages/elements/src/photon-multirx-form/index.tsx
https://www.notion.so/photons/If-no-patient-id-is-present-only-show-patient-card-92bf43b5fb784eb5b06b766b4384d7c0?pvs=4
> Select a patient before seeing the rest of the prescribe workflow

- packages/components/src/particles/Text/index.tsx
- packages/components/src/systems/PatientInfo/index.tsx
ref https://www.notion.so/photons/Update-Patient-Card-Info-ec81f26e92bc4d9b998b1d100be955fd?pvs=4
> Update patient card layout

- packages/settings/src/lib/photon.ts
> Enable One more Rx + Order Flow

- packages/settings/src/lib/photon.ts
> Neutron: Last Order + Rx

- packages/settings/src/lib/photon.ts
> Photon: Last Order + Rx

- packages/settings/src/lib/photon.ts
> Neutron: Rollback

- packages/settings/src/lib/photon.ts
> Photon: Rollback one customer

- apps/app/src/views/routes/Main.tsx
- package-lock.json
- package.json
- packages/components/dev/App.tsx
- packages/components/src/index.css
- packages/components/src/index.ts
- packages/components/src/particles/Card/index.tsx
- packages/components/src/systems/SDKProvider/index.tsx
- packages/components/src/utils/toastTriggers.tsx
- packages/elements/src/photon-client/index.tsx
- packages/elements/src/photon-form-wrapper/index.tsx
- packages/elements/src/photon-multirx-form-wrapper/index.tsx
- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
- packages/settings/src/lib/photon.ts
> Photon: Toast messages

- apps/app/src/App.tsx
- apps/app/src/views/components/Zendesk.tsx
- apps/app/tsconfig.json
- apps/app/types/zendesk.d.ts
- packages/components/src/particles/Dialog/index.tsx
> Neutron: Zendesk meta data

- apps/app/src/App.tsx
- apps/app/src/views/components/Zendesk.tsx
- apps/app/tsconfig.json
- apps/app/types/zendesk.d.ts
- packages/components/src/particles/Dialog/index.tsx
> Photon: Zendesk mete data

- packages/sdk/src/types.ts
> add new permissions

- apps/app/src/views/routes/NewOrder/index.tsx
> Neutron: change Background

- apps/app/src/views/routes/Patients.tsx
- packages/components/src/index.css
- packages/elements/src/photon-form-wrapper/index.tsx
- packages/elements/src/photon-multirx-form-wrapper/index.tsx
- packages/elements/src/photon-patient-form/index.tsx
- font weight fix
- patient form width
> Prescribe flow cosmetic 💄

- packages/settings/src/lib/neutron.ts
- packages/settings/src/lib/photon.ts
Fulfills [this request](https://photonhealth.slack.com/archives/C02V18YAEE9/p1699897226710979). Now they have combined flow disabled on neutron and photon.
> Enable combined flow for piction neutron

- packages/elements/src/photon-multirx-form/index.tsx
- packages/elements/src/photon-multirx-form/util/clearForm.ts
Readd templates on prescription creation #663
> Neutron: Re-add templates on prescription creation

- apps/patient/src/components/Nav.tsx
- apps/patient/src/views/Main.tsx
- apps/patient/src/views/Pharmacy.tsx
- apps/patient/src/views/Review.tsx
- apps/patient/src/views/Status.tsx
- bottom padding on pizza tracker
- remove logo flicker
> Patient UI polishing

- apps/patient/src/components/Nav.tsx
- apps/patient/src/views/Main.tsx
- apps/patient/src/views/Pharmacy.tsx
- apps/patient/src/views/Review.tsx
- apps/patient/src/views/Status.tsx
- packages/elements/src/photon-multirx-form/components/PatientCard.tsx
- packages/elements/src/photon-multirx-form/index.tsx
Patient UI polishing #666
Hide address form on prescription only form #667
> Neutron: Patient UI polishing, remove prescribe-only address requirement

- apps/patient/src/components/Nav.tsx
- apps/patient/src/views/Main.tsx
- apps/patient/src/views/Pharmacy.tsx
- apps/patient/src/views/Review.tsx
- apps/patient/src/views/Status.tsx
- packages/elements/src/photon-multirx-form/components/PatientCard.tsx
- packages/elements/src/photon-multirx-form/index.tsx
Patient UI polishing #666
Hide address form on prescription only form #667
> Photon: Patient UI polishing, remove prescribe-only address requirement

- apps/patient/src/views/Status.tsx
- packages/sdk/src/types.ts
Option to set picked up was not surfacing in READY fulfillment state. I think this was just an oversight. At first we based off of order state, then fulfillment Received, should have been received/ready.
> Fix set "picked up" not showing in ready

- apps/patient/src/views/Status.tsx
- packages/sdk/src/types.ts
Fix set "picked up" not showing in ready #670
> Neutron: Fix set picked up in Ready

- apps/patient/src/views/Status.tsx
- packages/sdk/src/types.ts
Fix set "picked up" not showing in ready #670
> Photon: Fix set picked up in Ready

- apps/patient/src/views/Status.tsx
- packages/settings/src/lib/boson.ts
- packages/settings/src/lib/neutron.ts
- packages/settings/src/lib/photon.ts
- packages/settings/src/types.ts
Enable med history, combined flow and pt rerouting to otto's demo org
> Update otto's demo org settings

- apps/app/src/configs/theme.ts
- apps/app/src/views/components/Logo.tsx
- apps/app/src/views/components/Nav.tsx
- apps/app/src/views/components/NavButton.tsx
- apps/app/src/views/routes/Login.tsx
- apps/app/src/views/routes/Prescriptions.tsx
present 
future
[figma ref](https://www.figma.com/file/nfV101GDuTUl2Fu02Uq4dq/Prescribe-App?type=design&node-id=1259%3A4121&mode=design&t=3bzpSp0KXRgpBto8-1)
> better hetter

- apps/app/src/configs/theme.ts
- apps/app/src/views/components/Logo.tsx
- apps/app/src/views/components/Nav.tsx
- apps/app/src/views/components/NavButton.tsx
- apps/app/src/views/routes/Login.tsx
- apps/app/src/views/routes/Prescriptions.tsx
- apps/app/src/views/routes/Settings/components/client-credentials/Credentials.tsx
- apps/app/src/views/routes/Settings/components/organization/Organization.tsx
- apps/app/src/views/routes/Settings/index.tsx
https://github.com/Photon-Health/client/pull/688
https://github.com/Photon-Health/client/pull/689
> Neutron: avatar menu neutron

- apps/app/src/views/routes/Settings/components/users/UsersList.tsx
@jknapp25 pointed out that we need to make the sort affordance obvious
> user table cursor pointer

- .github/workflows/auto-bump-neutron.yml
If I did this right, it should open a PR on neutron with a merge after boson is merged
> attempt to auto-bump neutron

- packages/settings/src/lib/neutron.ts
- packages/settings/src/lib/photon.ts
Flip the default from separate flow to combined (prescribe + order) to aid in the migration toward combined.
> Make combined flow the default

- .github/workflows/auto-bump-neutron.yml
- apps/app/src/views/routes/Settings/components/users/UsersList.tsx
- packages/settings/src/lib/neutron.ts
- packages/settings/src/lib/photon.ts
Make combined flow the default #712
user table cursor pointer #707
> Neutron: Default to combined flow

- .github/workflows/auto-bump-neutron.yml
- apps/app/src/views/routes/Settings/components/users/UsersList.tsx
- packages/settings/src/lib/neutron.ts
- packages/settings/src/lib/photon.ts
Make combined flow the default https://github.com/Photon-Health/client/pull/712
user table cursor pointer https://github.com/Photon-Health/client/pull/707
> Photon: Default to combined flow

- apps/patient/src/api/external.ts
- apps/patient/src/components/PharmacyCard.tsx
- apps/patient/src/utils/general.ts
- apps/patient/src/views/Pharmacy.tsx
🚗  Took a roadtrip around the US and caught a few edge-cases (souvenirs).
> Internal hours follow-up

- apps/app/src/index.tsx
- apps/app/src/views/components/NameView.tsx
- packages/components/src/systems/PatientInfo/index.tsx
Some updates to datadog session replays on the clinical app
> Update clinical app session replay config

- apps/app/src/views/routes/Settings/components/invites/InviteItem.tsx
Copy cleanup on the delete invite confirmation modal
> Delete invite ui polishing

- apps/app/src/views/components/ContactView.tsx
- apps/app/src/views/routes/NewOrder/components/PatientCard.tsx
- apps/app/src/views/routes/Patient.tsx
- packages/components/src/systems/PatientInfo/index.tsx
Additional refining of our data masking for datadog session replay's.
> Improve provider app data masking

- apps/patient/src/api/external.ts
- apps/patient/src/api/internal.ts
- apps/patient/src/components/PharmacyCard.tsx
- apps/patient/src/components/PharmacyFilters.tsx
- apps/patient/src/components/PickupOptions.tsx
- apps/patient/src/configs/theme.ts
- apps/patient/src/graphql/queries.ts
- apps/patient/src/utils/text.ts
- apps/patient/src/views/Pharmacy.tsx
- apps/patient/src/views/Review.tsx
Refetch pharmacies with filter criteria when filter enabled. Also some copy updates, pluralization, cleanup.
https://github.com/Photon-Health/client/assets/3934326/170b30c1-d08b-4f2f-a231-dddfa6752dad
> Pharmacy selection filters

- packages/settings/src/lib/photon.ts
> Setup Burdoin Mtn Medicine

- apps/patient/src/components/BrandedPharmacyCard.tsx
- apps/patient/src/views/Pharmacy.tsx
Update capsule description to show same day copy nationwide
> Capsule nationwide same day

- apps/patient/src/components/BrandedPharmacyCard.tsx
- packages/settings/src/lib/neutron.ts
We can't login to sesame so setting otto's org branding to Sesame and enabling costco option. I'm going up to neutron with this so we can make a demo.
> More Sesame demo prep

- apps/app/src/views/routes/Settings/components/templates/TemplateTable.tsx
> 0 paginate

- apps/app/src/views/components/Nav.tsx
> menu user tweak

- apps/patient/src/components/Nav.tsx
- apps/patient/src/data/demoPharmacies.ts
- apps/patient/src/views/Main.tsx
- apps/patient/src/views/Pharmacy.tsx
Some gaps were created after introducing filters and internal hours. Juggling the demo needs some refactoring, but this gets it running.
> Demo fixes

- apps/patient/src/views/Main.tsx
- apps/patient/src/views/Status.tsx
- fix missing demo rx's
- speed up status transitions
> Fix demo rx's not showing

- apps/patient/src/components/StatusStepper.tsx
- apps/patient/src/utils/text.ts
I missed one mail order fulfillment state in my recent status updates.
> Fix mail order header missing on FILLING

- apps/patient/src/components/StatusStepper.tsx
- apps/patient/src/utils/text.ts
> Neutron: Fix mail order header missing on FILLING

- apps/patient/src/components/StatusStepper.tsx
- apps/patient/src/utils/text.ts
Cherrypicked some commits for the status stepper fix to exclude the ITP changes.
> Neutron: Fix status stepper states

- packages/sdk/src/utils.ts
Fix for users tables not loading
> Neutron: Remove trailing slash from photon url

- packages/components/src/store.ts
- packages/components/src/systems/Client/index.tsx
- packages/elements/src/photon-authenticated/index.tsx
- packages/elements/src/photon-client/index.tsx
- packages/elements/src/store.ts
Move the auto-login logic to the store.
> more sane auto-login

- apps/patient/src/utils/text.ts
> Remove asap urgency

- apps/patient/src/views/Urgency.tsx
...to keep selection in view when footer appears.
https://github.com/Photon-Health/client/assets/3934326/63046e88-8127-43a6-8956-d66a50a7261e
> Scroll to bottom on urgency selection

- packages/elements/package.json
Thought this went out with https://github.com/Photon-Health/client/pull/839
> Bump Elements for External Order Id

- packages/components/src/store.ts
- packages/components/src/systems/Client/index.tsx
- packages/elements/src/photon-authenticated/index.tsx
- packages/elements/src/photon-client/index.tsx
- packages/elements/src/store.ts
Should be a revert of https://github.com/Photon-Health/client/pull/803/files
> revert #803

- packages/elements/package.json
- packages/elements/src/photon-client/index.tsx
So there WAS a bug here. These two code paths need to be mutually exclusive
> small refactor for login logic

- apps/patient/src/views/Urgency.tsx
> Polish disabled urgency card ui for clarity

- packages/elements/src/photon-treatment-select/index.tsx
https://www.notion.so/photons/Preload-Med-List-In-Prescribe-Flow-5a519657b34d4a62830437c74d3af0d2?pvs=4
> Don't show "no treatments" when treatments are loading

- apps/patient/src/utils/text.ts
- apps/patient/src/views/Urgency.tsx
Testing an urgent option added to the bottom of urgency options
> Add urgent option

- apps/patient/src/components/StatusStepper.tsx
Ran locally this time and tested that it works
> HOTFIX: Fix headers

- apps/patient/src/components/StatusStepper.tsx
- apps/patient/src/utils/text.ts
Walking back Sam's status stepper hot fix that's currently on photon
> Fix status stepper for mail order

- apps/patient/src/components/StatusStepper.tsx
- apps/patient/src/views/Status.tsx
- fix subheader not a function for mail order filling
- correctly show patient address on delivery states
> Fix mail order FILLING status details

- apps/app/src/views/routes/Main.tsx
- package-lock.json
- package.json
Testing if this is why RUM with open shadow dom web components hasn't been working.
> Upgrade datadog to the latest

- apps/patient/src/views/Main.tsx
A bit of helpful metadata for finding sessions/actions/replays
> Add patient/org to rum

- .github/workflows/merge-bot.yml
- .vscode/extensions.json
- apps/app/src/views/components/TablePage.tsx
https://www.notion.so/photons/List-Page-is-throwing-unique-key-error-f1d161f2484145bf93fe418a311a1436?pvs=4
> Fix unique key error on table page

- .eslintrc.json
- apps/app/src/views/routes/SelectOrg.tsx
- package-lock.json
- packages/react/src/provider.tsx
https://legacy.reactjs.org/docs/hooks-rules.html
https://medium.com/@ryardley/react-hooks-not-magic-just-arrays-cd4f1857236e
> enforce and fix react hook rules

- .eslintrc.json
- .github/workflows/merge-bot.yml
- .vscode/extensions.json
- apps/app/src/model/fragments.ts
- apps/app/src/views/components/MedicationSelect.tsx
- apps/app/src/views/components/TablePage.tsx
- apps/app/src/views/routes/NewOrder/index.tsx
- apps/app/src/views/routes/SelectOrg.tsx
- apps/app/src/views/routes/Settings/components/templates/TemplateActions.tsx
- apps/app/src/views/routes/Settings/components/templates/TemplateForm/index.tsx
- apps/app/src/views/routes/Settings/components/treatments/TreatmentActions.tsx
- apps/app/src/views/routes/Settings/views/TemplateTab.tsx
- apps/app/src/views/routes/Settings/views/TreatmentTab.tsx
- package-lock.json
- packages/components/src/store.ts
- packages/components/src/systems/RecentOrders/RecentOrders.tsx
- packages/components/src/systems/RecentOrders/RecentOrdersCombineDialog.tsx
- packages/components/src/systems/RecentOrders/RecentOrdersIssueDialog.tsx
- packages/components/src/utils/createMutation.ts
- packages/components/src/utils/createQuery.ts
- packages/components/src/utils/uniqueFills.ts
- packages/elements/src/store.ts
- packages/elements/src/stores/catalog.ts
- packages/react/src/provider.tsx
- packages/sdk/src/fragments.ts
- packages/sdk/src/lib.ts
- packages/settings/src/lib/neutron.ts
Reverts Photon-Health/client#910 and then merges in from neutron
> Revert "Revert photon deploy"

- packages/elements/src/photon-dropdown/index.tsx
> Padding the loading: this has been bothering me for months

- apps/patient/src/App.tsx
- apps/patient/src/views/Review.tsx
Closing out the urgent at bottom test. Export added to ticket.
> Remove urgent at bottom test

- packages/elements/src/photon-card/photon-card-component.tsx
- packages/elements/src/photon-datepicker/photon-datepicker-component.tsx
- packages/elements/src/photon-datepicker/style.css
- packages/elements/src/photon-dispense-units/photon-dispense-units-component.tsx
- packages/elements/src/photon-dropdown/photon-dropdown.tsx
- packages/elements/src/photon-dropdown/style.css
- packages/elements/src/photon-gender-input/style.css
- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
- packages/elements/src/photon-multirx-form/style.css
- packages/elements/src/photon-multirx-form/util/clearForm.ts
- packages/elements/src/photon-number-input/photon-number-input-component.tsx
- packages/elements/src/photon-number-input/style.css
- packages/elements/src/photon-patient-select/style.css
- packages/elements/src/photon-phone-input/photon-phone-input-component.tsx
- packages/elements/src/photon-phone-input/style.css
- packages/elements/src/photon-sex-input/style.css
- packages/elements/src/photon-state-input/style.css
- packages/elements/src/photon-text-input/photon-text-input-component.tsx
- packages/elements/src/photon-text-input/style.css
- packages/elements/src/photon-textarea/photon-textarea-component.tsx
- packages/elements/src/photon-textarea/style.css
https://www.notion.so/photons/Dispense-unit-defaulting-to-Each-causes-clinical-issues-with-prescription-8ed4dba93852435b93dba7e08700cb3a?pvs=4
> Dispense Unit should not default to "Each"

- apps/patient/src/utils/text.ts
- apps/patient/src/views/Pharmacy.tsx
- apps/patient/src/views/Urgency.tsx
On pharmacy selection cta:
Select a pharmacy -> Select pharmacy
> Update pharmacy selection cta copy

- apps/app/src/views/routes/Login.tsx
- packages/elements/src/photon-authorized/photon-authorized.tsx
https://www.notion.so/photons/Update-login-page-copy-for-users-who-can-t-log-in-to-reach-out-to-their-admin-da9718f243e64f4a9b361b3826f492a9?pvs=4
> Updated Auth Alert Message

- apps/patient/src/components/PharmacyCard.tsx
- apps/patient/src/utils/general.ts
- apps/patient/src/utils/models.ts
- apps/patient/src/utils/text.ts
> Add closing soon to pharmacy option

- apps/patient/src/components/Nav.tsx
- packages/settings/src/lib/boson.ts
- packages/settings/src/lib/neutron.ts
> Default to photon logo without org logo

- packages/elements/src/photon-client/photon-client-component.tsx
- packages/settings/src/lib/neutron.ts
Also include adding gogo to neutron org
> Revert autologin fix

- apps/patient/src/utils/text.tsx
- apps/patient/src/views/NoMatch.tsx
> Fix SMS link in the Patient App

- apps/patient/src/views/Main.tsx
Makes it a little more convenient to troubleshoot issues on orders
> Add orderId to Datadog session tracking

- packages/settings/src/lib/photon.ts
> Add empower pharmacy mail order option for DrTelx

- apps/app/src/views/routes/PrescriptionForm.tsx
- packages/elements/package.json
- packages/elements/src/photon-multirx-form/photon-prescribe-workflow-component.tsx
- packages/settings/src/lib/boson.ts
- packages/settings/src/lib/neutron.ts
- packages/settings/src/lib/photon.ts
- packages/settings/src/types.ts
https://photonhealth.slack.com/archives/C033T9N949M/p1709924313728449
> Hide Templates defaults to false in elements

- packages/settings/src/lib/neutron.ts
https://photonhealth.slack.com/archives/C05NXJ4KW2H/p1710175019352499?thread_ts=1706886313.632739&cid=C05NXJ4KW2H
> Sana Med History Card on Neutron

- apps/app/src/views/routes/Settings/components/users/EditRolesAction.tsx
https://www.notion.so/photons/Updating-user-roles-not-working-6ac08cda4c0f49e1baaa9c0ff20fd491?pvs=4
> Fix, Updating user roles not working

- .github/workflows/add-comment.yml
- .github/workflows/upload-source-maps-to-datadog.yml
- apps/patient/config-overrides.js
- package-lock.json
- package.json
First-pass setup for uploading source maps to Datadog for better code mapping on our errors. Just frontend errors at first.
Todo:
> Upload source maps to Datadog

- apps/patient/src/components/PharmacyCard.tsx
- apps/patient/src/utils/general.ts
- fix pharmacy missing hrs showing up as closed
- make am/pm formatting consistent with urgency
> Fix missing hrs showing as closed pharmacy

- packages/components/src/systems/LocationSelect/index.tsx
- packages/components/src/systems/PharmacySearch/index.tsx
- packages/components/src/utils/asyncInterval.ts
- packages/elements/package.json
https://photonhealth.slack.com/archives/C05UCJ4FZAN/p1710433874075989
> Fix Geocoder race condition with standalone elements

- .github/workflows/upload-source-maps-to-datadog.yml
Seeing more errors on the clinical app so this will help me get these setup quicker.
> Add clinical app source maps

- .github/workflows/upload-source-maps-to-datadog.yml
> Extract env into variable in source map upload

- packages/components/dev/App.tsx
- packages/components/src/systems/PatientMedHistory/index.tsx
- packages/elements/package.json
https://photonhealth.slack.com/archives/C05UCJ4FZAN/p1710779082102259
BEFORE
AFTER
> Hide Medical History Status Column

- packages/elements/package.json
https://github.com/Photon-Health/client/pull/1040
> Bump Elements version for "Pass entire order for order combined event #1040"

- apps/patient/src/views/Canceled.tsx
One more, missed it in this previous fix:
https://github.com/Photon-Health/client/pull/1008
> Fix another SMS link in the Patient App

- package-lock.json
- packages/settings/src/lib/neutron.ts
> Enable Costco for Sesame on neutron

- apps/app/src/views/components/NameView.tsx
- apps/app/src/views/components/Nav.tsx
- apps/app/src/views/components/TablePage.tsx
- apps/app/src/views/routes/Prescription.tsx
- apps/app/src/views/routes/Prescriptions.tsx
A few small changes to handle the chakra ui updates that came in with upgrade. Mostly adding back missing backgrounds and fixing badges.
> Polish clinical UI

- apps/app/src/views/routes/Orders.tsx
> Patient Link broken on Order list page

- apps/app/public/.well-known/microsoft-identity-association.json
Will be used to verify our domain with microsoft
> Add .well-known file for microsoft app

- apps/patient/src/utils/general.ts
- apps/patient/src/utils/text.tsx
- apps/patient/src/views/ReadyBy.tsx
Silly miss on my part here. Just not using the right dayjs for tomorrow.
> Fix readyByTime translation to UTC timestamp

- apps/patient/src/components/Prescriptions.tsx
- apps/patient/src/components/PrescriptionsList.tsx
- apps/patient/src/utils/text.tsx
- apps/patient/src/views/Canceled.tsx
- apps/patient/src/views/Main.tsx
- apps/patient/src/views/NoMatch.tsx
- apps/patient/src/views/Review.tsx
https://www.notion.so/photons/Create-more-robust-Order-Cancelled-Page-for-Patient-App-c6d89f6598914d4f8869e861b86e9596?pvs=4
> Better Order Cancelled Page

- packages/sdk/README.md
Updating this before we share SDK with a customer
> Update SDK Readme to demonstrate how to check if a user is Authenticated

- packages/settings/src/lib/photon.ts
Seeing UX issue on Urgent Blueberry selections, disabling this feature till we have a fix.
> Disable topRankedWalgreens for Blueberry

- apps/patient/src/components/PharmacyCard.tsx
- apps/patient/src/utils/general.ts
- apps/patient/src/utils/models.ts
- apps/patient/src/views/Pharmacy.tsx
- apps/patient/src/views/Status.tsx
- packages/settings/src/lib/photon.ts
For the Walgreens Urgency Pilot, all Walgreens pharmacy options should have the "Ready in 30 minutes" badge not just the top ranked one.
> Add 30 min badge to all Walgreens pharmacies

- apps/patient/src/views/Status.tsx
Fix the last 2 of 4 sms that the demo sends
> Fix order received/ready demo sms'

- packages/elements/package.json
version for https://github.com/Photon-Health/client/pull/1114
> Bump elements for RollBack

- apps/patient/src/components/BrandedOptions.tsx
- apps/patient/src/components/BrandedPharmacyCard.tsx
- apps/patient/src/components/PickupOptions.tsx
- apps/patient/src/utils/text.tsx
- apps/patient/src/views/Pharmacy.tsx
Subheader and branded pharmacy subtext updates.
> Copy refinements on delivery vs local

- packages/settings/src/lib/neutron.ts
Testing org specific delivery config before going to prod
> Enable Sana delivery on neutron for testing

- apps/patient/src/components/BrandedPharmacyCard.tsx
cuz I'm a full-time copy editor 😆
> Sentence-case on delivery options subheaders

- apps/app/src/views/routes/Main.tsx
Ticket Ref
https://www.notion.so/photons/Handle-auth0-Error-States-on-Login-3486ee6a8e5d4c60a2db091f8f0cbd78?pvs=4
> Display an error for Auth0 Login invitation issue

- apps/app/src/views/routes/PrescriptionForm.tsx
- packages/elements/src/photon-med-search/photon-med-search-component.tsx
This will help us to discovery
https://www.notion.so/photons/Optimize-Sync-2f989a654ab0495aae3f975c2c80a4c7?pvs=4#dc1ae8d0183b4b09bc91b52394be10ae
> Allow us to understand which providers are using Advance Med search

- .github/workflows/upload-source-maps-to-datadog.yml
I was instructed by a DD support agent to try without the full dist path since DD can scan subdirectories
> Test sourcemap upload without full path

- apps/patient/src/views/Pharmacy.tsx
We're promoting Walmart to a top ranked pharmacy and hanging a picture on the wall 🖼
> Show Walmart with med price up top

- apps/patient/src/views/Pharmacy.tsx
Show Walmart with med price up top [#1148](https://github.com/Photon-Health/client/pull/1148)
> Re-deploy Walmart up top

- apps/app/src/views/components/Page.tsx
- apps/app/src/views/routes/Settings/components/users/UsersList.tsx
- apps/patient/src/views/Review.tsx
Frontend errors aren't coming in right now, good problem to have, so I added some errors here and there to test source maps.
> Source map error testing

- apps/app/src/views/components/Page.tsx
- apps/app/src/views/routes/Settings/components/users/UsersList.tsx
- apps/patient/src/views/Review.tsx
Just removing my testing triggers
> Remove source map error triggers

- packages/elements/src/photon-dropdown/photon-dropdown.tsx
https://www.notion.so/Treatment-Input-has-suggested-inputs-aea44f8826f14ba2a991d51960100482?pvs=4
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
> No autocomplete in the dropdowns

- packages/settings/src/lib/boson.ts
- packages/settings/src/lib/neutron.ts
- packages/settings/src/lib/photon.ts
Also remove ...defaultSettings from needing to be in each object
> Add settings for Great Many

- apps/patient/src/components/BrandedPharmacyCard.tsx
- apps/patient/src/components/FAQ.tsx
- apps/patient/src/components/HorizontalStatusStepper.tsx
- apps/patient/src/components/PrescriptionsList.tsx
- apps/patient/src/utils/text.tsx
- apps/patient/src/views/Status.tsx
A condensed flavor of our beloved pizza tracker as well as some small UI polishing on the status page. Showing ready by time is on deck.
> Condensed status stepper

- packages/elements/package.json
I updated the github action, trying to set this https://github.com/Photon-Health/client/pull/1187
> Retriggering RC for Double Reload

- apps/patient/src/components/PharmacyCard.tsx
- apps/patient/src/components/PickupOptions.tsx
Add holiday hours disclaimer on pickup pharmacy selection that hours may be different. It'll surface all weekend before a holiday if the holiday is on a monday.
> Add holiday hours disclaimer

- apps/app/src/views/routes/Settings/components/users/EditRolesAction.tsx
Request from a customer, simple to expose since the design on this page needs to be rethough later any way
> Add user id to settings page

- packages/settings/src/lib/photon.ts
A couple settings updates for the Great Many org. How many? Not that many. Just two.
> Set local and STP for Great Many on photon

- packages/components/src/index.ts
- packages/components/src/particles/ComboBox/index.tsx
- packages/components/src/particles/Input/index.tsx
- packages/components/src/systems/PharmacySelect/PharmacySelect.tsx
- packages/elements/src/photon-med-search/components/MedicationConceptDropdown.tsx
- packages/elements/src/photon-med-search/components/MedicationFilterDropdown.tsx
- packages/elements/src/photon-med-search/photon-med-search-component.tsx
- packages/elements/src/photon-patient-form/photon-patient-form-component.tsx
- packages/settings/src/lib/photon.ts
This is second attempt of this https://github.com/Photon-Health/client/pull/1219 [dropdown being hidden on mobile. ](https://photonhealth.slack.com/archives/C033T9N949M/p1718152280392819)
BEFORE
NOW
> Adv med dropdown fix

- packages/components/dev/App.tsx
once this goes through https://github.com/Photon-Health/terraform/pull/1851
is there a better way??
> WS to retrigger Neutron build

- apps/patient/src/utils/general.ts
- apps/patient/src/views/Main.tsx
We had an extra `countFillsAndRemoveDuplicates` call which reset the refill count back to 0, removed that
> Fix refill count incorrect on patient app

- packages/elements/package.json
handle infinite spinner issue in local pickup tab #1247
> Bump elements

- packages/elements/package.json
- packages/elements/src/photon-multirx-form/components/DraftPrescriptionCard.tsx
A customer needs to [handle draft prescriptions being deleted](https://photonhealth.slack.com/archives/C04E8BD61SA/p1721084149566689) from the pending order.
> Dispatch Draft Prescription Delete Event

- packages/elements/package.json
Forgot to bump it in the last PR
https://github.com/Photon-Health/client/pull/1271
> Version Bump for Refills max

- apps/patient/src/components/BrandedPharmacyCard.tsx
FREE, come get it baby!
We're doing a tiny copy variation as a test.
> Same day capsule sesame test

- apps/patient/src/components/BrandedPharmacyCard.tsx
- packages/elements/package.json
- packages/elements/src/photon-dropdown/photon-dropdown.tsx
- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
https://photonhealth.slack.com/archives/C05LVD54ZC0/p1721775359546099
> Photon: Revert Virtualizer

- apps/patient/src/components/BrandedPharmacyCard.tsx
Misunderstanding on my part, I thought these were two different tests.
> Update Capsule test copy to "Free Same or Next Day Delivery"

- apps/patient/src/components/BrandedPharmacyCard.tsx
- packages/elements/package.json
- packages/elements/src/photon-dropdown/photon-dropdown.tsx
- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
Reverts Photon-Health/client#1278
> Revert "Photon: Revert Virtualizer"

- apps/patient/src/components/BrandedOptions.tsx
- apps/patient/src/components/BrandedPharmacyCard.tsx
- apps/patient/src/components/PharmacyInfo.tsx
- apps/patient/src/components/PickupOptions.tsx
- apps/patient/src/utils/text.tsx
Next test to highlight capsule even more so.
Design:
> Highlight capsule even more

- apps/patient/src/components/ReadyText.tsx
- apps/patient/src/graphql/queries.ts
- apps/patient/src/views/Status.tsx
- fix pharmacyEstimatedReadyAt saying tomorrow when it was today, [nice catch Roch!](https://photonhealth.slack.com/archives/C02V18YAEE9/p1722517862309629)
- simplify this logic
> Cleanup ready time formatting

- apps/patient/src/components/BrandedPharmacyCard.tsx
- apps/patient/src/components/PharmacyInfo.tsx
- apps/patient/src/views/Pharmacy.tsx
We're going to run this test to see if a white-labeled delivery option (still Capsule) is more/less appealing to consumers.
> New test for a white-labeled delivery option

- apps/patient/src/views/Pharmacy.tsx
- packages/settings/src/lib/neutron.ts
- packages/settings/src/lib/photon.ts
Now that we have a week of data, we're closing out our latest capsule test around a white-labeled courier option. 
Results can be found [here](https://metrics.photon.health/dashboard/71-capsule-x-sesame-nationwide-white-labeled).
> Remove white-labeled capsule test

- packages/settings/src/lib/photon.ts
They're requiring we do production testing
> Add redrock to Photon test account

- packages/elements/src/photon-multirx-form/components/PatientCard.tsx
This was a pain. Because `PatientInfo` owns its own data and because `components` and `elements` don't share a store, the only way to force-retrigger is a rerender is to clear out the patientId and then reset it. But because solid does batching, you also need to set a timeout.
Also added a drop of types
> fix edit patient bug to make sure name is actually updated

- apps/app/src/views/routes/Settings/components/utils/Roles.tsx
https://www.notion.so/photons/Filtering-Roles-doesn-t-work-5326bb49b5864b43b24359901a8861df?pvs=23
https://github.com/user-attachments/assets/238f7418-ba5f-4f1b-92c1-568e90f1f62c
> filter roles

- apps/patient/src/graphql/queries.ts
We ran into a performance issue, so hardcoding 100 miles
> hardcode 100 miles

- apps/patient/src/graphql/queries.ts
Reverts Photon-Health/client#1323
> Revert "hardcode 100 miles"

- apps/patient/src/api/internal.ts
> fix radius

- .github/workflows/add-comment.yml
> patient app preview comment

- apps/app/src/views/routes/Patient.tsx
Fix (some) navigation when navigating using external ids.
https://www.notion.so/photons/Engineering-To-Do-99b385f35b914b13890fe9a48b6f612b?p=f9a109d4a76c44bf8be6708b0f0eb227&pm=s
Note this is essentially a hack. There are a few things we should do to improve this:
- If we're going to treat external ids and our ids as equivalent, we should make all backend pieces treat them equivalently. 
- We should probably add a client-side library that does similar swapping.
Also, in a followup PR, I'm going to fix the types on `getPatient` and other methods. They currently say they return `{ patient: Patient }` but because of the react lifecycle, should actually be `patient?: Patient`
> fix navigation by patient id in clinical app

- package-lock.json
- packages/elements/package.json
- packages/elements/src/photon-multirx-form/photon-prescribe-workflow.tsx
This is so Masslight can use the release candidate.
> Enable med search for all users

- packages/elements/package.json
- packages/elements/src/photon-multirx-form/photon-prescribe-workflow.tsx
Re-adding the flag for specific med search testers.
> Feature flag for specific med search testers

- packages/elements/src/photon-multirx-form/photon-prescribe-workflow.tsx
Added Muthu alongside Rishi to give new med search a go.
> Add additional Counsel provider for med search testing

- packages/elements/src/photon-multirx-form/photon-prescribe-workflow.tsx
Ali, Sara, Kelsey, Grace, new kids on the block
> Add 4 med search testers

- packages/elements/package.json
- packages/elements/src/photon-multirx-form/photon-prescribe-workflow.tsx
> Add Ognomy provider to new med search users

- packages/elements/src/photon-multirx-form/photon-prescribe-workflow.tsx
Enabling new med search for Caitlyn and Melissa
> Add ops to new med search

- apps/app/src/views/routes/PrescriptionForm.tsx
- packages/components/src/particles/Banner/Banner.stories.tsx
- packages/components/src/particles/Banner/index.tsx
- packages/elements/index.html
- packages/elements/src/photon-multirx-form-wrapper/photon-multirx-form-wrapper-component.tsx
- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
- packages/elements/src/photon-multirx-form/photon-prescribe-workflow-component.tsx
- packages/elements/src/photon-multirx-form/photon-prescribe-workflow.tsx
Style can be tweaked, but functionality allows for a closable educational banner.
This will release the new med search to all App users
> Release med search on clinical app

- packages/elements/package.json
- packages/elements/src/photon-medication-search/photon-medication-search-component.tsx
https://photonhealth.slack.com/archives/C02V18YAEE9/p1727284924730709
> Add template name in search

- apps/patient/src/views/Main.tsx
- apps/patient/src/views/Pharmacy.tsx
On the status page the pharmacy was sometime empty when selecting a pharm with discount cards. This fixes that.
> Fix pharmacy missing on status page with coupons

- apps/app/src/views/routes/Settings/components/treatments/TreatmentOptionSearch.tsx
a dangling semicolon snuck in, let's remove it
> fixed dangling semicolon

- apps/patient/src/api/internal.ts
- apps/patient/src/components/Card.tsx
- apps/patient/src/components/Coupons.tsx
- apps/patient/src/components/FAQ.tsx
- apps/patient/src/components/index.tsx
- apps/patient/src/graphql/mutations.ts
- apps/patient/src/graphql/queries.ts
- apps/patient/src/views/Pharmacy.tsx
- apps/patient/src/views/StatusV2.tsx
We updated the discount cards table with this flag so that we can better track price selections.
- Now passing `patientSelectedPrice` into rerouteOrder and setOrderPharmacy
- Updated status page to ensure we're showing a discount card for the current pharmacy
- Also did a lil pre-work for when we'll have multiple discount cards. It's not clear yet when we'll do this, maybe in the next month or so, I'm fine with removing, but felt nice to have
> Save patientSelectedPrice flag

- .husky/pre-commit
- .vscode/settings.json
- apps/patient/src/components/order-summary/OrderSummary.tsx
- package-lock.json
- packages/settings/src/lib/boson.ts
- packages/settings/src/lib/neutron.ts
- packages/settings/src/lib/photon.ts
- packages/settings/src/types.ts
> PA language for sesame plus precommit fix

- apps/patient/src/components/PickupOptions.tsx
- apps/patient/src/views/Pharmacy.tsx
In Florida and Georgia, show hurricane message on pharmacy selection page
> show banner for hurricane

- .github/workflows/merge-bot.yml
@billoran8 said he likes "ready to merge" as the label name.
https://www.notion.so/photons/Update-ready-label-in-client-to-be-ready-for-merge-1118bfbbf4ec80d28c2fd964bd86acf5?pvs=23
> allow ready to merge label

- apps/patient/src/components/BrandedPharmacyCard.tsx
- apps/patient/src/views/Pharmacy.tsx
- apps/patient/src/views/StatusV2.tsx
- fix second 2 mail order pharms not showing up on status page if selected
- delivery subheader for cost plus
> Follow-up to sana care mail order

- apps/patient/src/components/order-summary/OrderSummary.tsx
- apps/patient/src/components/statusV2/Header.tsx
These new types arent actually being used yet, but putting this up so that we compile and we can revisit the language later
> add new exception types

- apps/patient/src/views/Pharmacy.tsx
Returning cash price search to be the first that surfaces in pharmacy selection
> Swap distance with cash price

- apps/patient/src/components/order-summary/OrderSummary.tsx
- packages/settings/src/lib/photon.ts
- packages/settings/src/types.ts
the messages come from this google sheet: https://docs.google.com/spreadsheets/d/1X6b1Pyio8FC2ZpLaKBfmlkEjsWKuYov-YhFe2k3HG6Q/edit?gid=0#gid=0
> add pa exception messages by organization

- packages/elements/src/photon-multirx-form/photon-prescribe-workflow.tsx
was heavily testing some stuff and didn't want to create prescriptions while verifying behavior but forgot to uncomment it out in the larger pr. whoops.
> remove console logs and unnecessary comment

- packages/components/src/particles/Banner/index.tsx
- packages/components/src/systems/ScreeningAlerts/ScreeningAlert.tsx
- packages/components/src/systems/ScreeningAlerts/ScreeningAlertAcknowledgement.tsx
- packages/components/src/systems/ScreeningAlerts/ScreeningAlertByEntity.tsx
- packages/elements/src/photon-multirx-form/photon-prescribe-workflow.tsx
updating some colors; adding some borders; fixing issue with skipping alerts when there's a recent order; also adding some datadog dispatches to get us metrics about what causes people to close or acknoweldge alerts (though i will also be adding similar metrics to the backend)
> Fix issue with combine orders with clinical alerting

- apps/app/src/views/components/Page.tsx
- apps/app/src/views/routes/SelectOrg.tsx
- apps/app/src/views/routes/Settings/components/treatments/TreatmentOptionSearch.tsx
Fixing card contrast against the backgrounds.
**Select org**
Before:
After:
**Catalog**
Before:
After:
> Fix missing white bg on select org and /settings/catalog cards

- apps/app/src/views/routes/Order.tsx
Artificial limit i added back in the stone age, no good reason for it.
> Remove 5 rx limit on order page

- packages/settings/src/lib/photon.ts
Requested by OpenLoop [here](https://photonhealth.slack.com/archives/C063WCVSR6D/p1732741681416539)
> Remove mail order option for openloop

- apps/patient/src/views/Main.tsx
Shortlink action. See https://github.com/Photon-Health/lambdas/pull/1823 and https://www.notion.so/photons/Track-shortlink-opens-1508bfbbf4ec802da387e0af63a44109
> shortlink action

- apps/patient/src/graphql/queries.ts
- apps/patient/src/utils/fulfillmentsHelpers.ts
- apps/patient/src/views/StatusV2.tsx
> Include carrier in mail order tracking link 

- apps/app/src/views/routes/Settings/components/templates/TemplateForm/components/DispenseQuantity.tsx
- apps/app/src/views/routes/Settings/components/templates/TemplateForm/utils.ts
https://www.notion.so/photons/Template-Editor-Doesn-t-allow-for-Fractional-Amounts-1308bfbbf4ec80e091c9fdbbde53609d?pvs=4
> Template Quantity can allows for values between 0 and 1 also

- apps/patient/src/components/Coupons.tsx
- apps/patient/src/data/demoOrder.ts
- apps/patient/src/graphql/queries.ts
- apps/patient/src/utils/text.tsx
Adding the below generic price disclaimer to add clarity around it potentially being different than branded price at the pharmacy.
> Show generic price disclaimer on discount card

- packages/components/src/systems/RecentOrders/RecentOrders.tsx
- packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx
- packages/elements/src/photon-multirx-form/components/DraftPrescriptionCard.tsx
- packages/sdk/package.json
- packages/sdk/project.json
https://github.com/user-attachments/assets/1c67e377-b82f-4561-afca-021dfde08c26
https://github.com/user-attachments/assets/61cdcc56-758f-4926-8abb-1c9388f2245c
> Only check for duplicate order fills on non canceled recent orders

- apps/patient/src/App.tsx
- apps/patient/src/components/Coupons.tsx
- apps/patient/src/components/PharmacyFilters.tsx
- apps/patient/src/components/PickupOptions.tsx
- apps/patient/src/utils/text.tsx
- apps/patient/src/views/Main.tsx
- apps/patient/src/views/PaymentMethod.tsx
- apps/patient/src/views/Pharmacy.tsx
- apps/patient/src/views/ReadyBy.tsx
- package-lock.json
- package.json
We're placing a decision point after readyBy and before pharmacy selection to determine if the patient actually wants to pay with cash or insurance. This test will likely result in fewer price selections, but should help us gauge intent of the patient better. Also might increase % adjudicated 🤞.
**New Payment Method view**
**How it looks on /pharmacy**
> 🍴 Price v Insurance Fork

- apps/patient/src/components/order-summary/OrderSummary.tsx
Just a lil due diligence here. We do this on the review page right now.
> Mask med names on status page for DataDog replays

- apps/patient/src/components/PharmacyFilters.tsx
- apps/patient/src/utils/general.ts
- apps/patient/src/views/PaymentMethod.tsx
- apps/patient/src/views/ReadyBy.tsx
For patients that saw the Cash Price v Insurance Copay, if they selected Cash Price, we still want them to have the option to filter by price.
> Show price flag in for all patients that saw the fork 🍴 

- apps/patient/src/components/order-summary/OrderSummary.tsx
- apps/patient/src/components/statusV2/Header.tsx
- apps/patient/src/components/statusV2/Step.tsx
- apps/patient/src/views/StatusV2.tsx
Also worked on spacing, text color/weight, justification, etc. to reflect design spec.
> Fix incorrect text on order placed sub-header

- apps/patient/src/views/Pharmacy.tsx
issue and fix replicated locally
> fixed an issue with pharmacies not loading in the demo

- apps/patient/src/views/Pharmacy.tsx
auto merging [doesn't seem to be having a great time](https://github.com/Photon-Health/client/actions/runs/12549279213/job/34990467548). in the interest of fixing the issue quickly i'm just going to do this and then look into the merging issue afterwards.
> fixing issue with demo loading pharmacies [manually applied on neutron branch]

- apps/patient/src/components/PharmacyFilters.tsx
- apps/patient/src/utils/general.ts
- apps/patient/src/views/ReadyBy.tsx
At some point our boson org name was changed, so I updated to check org id instead.
> fix boson not showing prices

- packages/elements/package.json
time to publish a new version of our elements so peeps can get the latest and greatest.
incrementing major version because it's dramatically enhancing the power of the medhistory component.
> incrementing version of elements

- apps/patient/src/components/Coupons.tsx
- apps/patient/src/components/order-summary/OrderSummary.tsx
The "This price is for generic medication only" subtitle is inaccurate since GLP1's are branded.
> Remove generic copy for glp1

- apps/patient/src/components/Coupons.tsx
- apps/patient/src/components/PharmacyFilters.tsx
- apps/patient/src/utils/isGLP.ts
- apps/patient/src/views/Pharmacy.tsx
- apps/patient/src/views/ReadyBy.tsx
Miscommunication w/ Sesame. Recalibrating, then we'll relaunch. 
Bit of a setback but we're marching on, lot's of refinements to pricing on-deck to test right now anyway.
> Hide Glp1 prices temporarily

- packages/elements/src/photon-form-wrapper/photon-form-wrapper.tsx
https://photonhealth.slack.com/archives/C02V18YAEE9/p1740151083873159
> Rollback Z-index change

- apps/app/src/views/routes/Order.tsx
- apps/patient/src/components/InsuranceAlert.tsx
- apps/patient/src/components/order-summary/OrderSummary.tsx
- apps/patient/src/components/statusV2/Header.tsx
- apps/patient/src/data/demoOrder.ts
- apps/patient/src/graphql/queries.ts
- apps/patient/src/views/StatusV2.tsx
grab exceptions on order object and display updates to header/status page if exceptions are present
> Order exceptions

- apps/patient/src/views/ReadyBy.tsx
Just a lil condition to make it so that Jomi can also test the new glp1 pricing changes.
> Allow us to test glp1s on boson

- apps/patient/src/utils/general.ts
- packages/elements/index.html
- packages/elements/package.json
- packages/elements/src/photon-multirx-form/components/PatientCard.tsx
- packages/elements/src/photon-multirx-form/photon-prescribe-workflow.tsx
Auto-pr is broken on photon. Manually created this pr to remove discount cards for sesame asap.
> Manually update photon

- apps/patient/src/components/PharmacyInfo.tsx
- apps/patient/src/views/StatusV2.tsx
1. makes the pharmacy address clickable and link to directions
2. makes `Call pharmacy` the primary button if there is an exception
> make pharmacy address link to directions, display call pharmacy for order exceptions

- apps/patient/src/api/external.ts
- apps/patient/src/api/internal.ts
- apps/patient/src/graphql/queries.ts
- apps/patient/src/views/Pharmacy.tsx
We no longer need it to fetch pharmacies
> cleanup residual zipcode prop

- apps/patient/src/components/Coupons.tsx
- apps/patient/src/components/PharmacyCard.tsx
- apps/patient/src/components/PharmacyInfo.tsx
- apps/patient/src/components/PickupOptions.tsx
- apps/patient/src/configs/theme.ts
- apps/patient/src/utils/general.ts
- apps/patient/src/utils/text.tsx
- apps/patient/src/views/Pharmacy.tsx
- packages/settings/src/lib/boson.ts
- packages/settings/src/lib/neutron.ts
- packages/settings/src/lib/photon.ts
- packages/settings/src/types.ts
- add showPrice setting
- ui polishing, pushed Link styling to chakra theme config
- some copy updates
> Make show price configurable in settings

- apps/patient/src/views/Pharmacy.tsx
> Ensure top ranked Costco for Sesame when there's Glp1 prices showing

- apps/patient/src/views/Main.tsx
- apps/patient/src/views/Pharmacy.tsx
Zepbound is by far the most prescribed, just starting here for now.
> Narrow scope to goodrx zepbound

- packages/settings/src/lib/neutron.ts
- packages/settings/src/lib/photon.ts
I forgot to flip the switch! lol
> Turn on Sesame pricing

- packages/components/dev/App.tsx
- packages/components/src/systems/Client/index.tsx
localhost:3000 had errors when running locally via `npx nx run components:start`
- fix 401 error from not setting clinical-api env in sdk
- use better test patientId
> Fix running components locally

- apps/patient/src/views/Pharmacy.tsx
We've tested the switch off, now we're testing it default on. I'm sure we'll see more price selections, it'll be interesting to see who turns it off.
> Make price switch default on

- package-lock.json
- package.json
- packages/elements/package.json
Using fix for a known npm build issue documented here: 
https://github.com/vitejs/vite/discussions/15532#discussioncomment-8527272
> Fix CI error for npm publish

- apps/patient/src/views/Main.tsx
https://www.notion.so/photons/Can-t-get-clickthrough-rate-for-new-customers-like-Visana-1b48bfbbf4ec8069b24fdaac7c2e2ea7?pvs=4
> Datadog Action should have organization id as well

- package-lock.json
- packages/components/README.md
- packages/components/src/systems/DoseCalculator/components/DoseCalculator.tsx
https://www.notion.so/photons/Dose-Calculator-accepts-negative-inputs-52fe5f8e47d341caa5a73b2643fa1a55
> Sets min value for dose calculator inputs

- apps/app/playwright.config.ts
* also re-added some useful comments
> Use correct base url for playwright startup

- apps/patient/src/views/Pharmacy.tsx
- packages/settings/src/lib/neutron.ts
- packages/settings/src/lib/photon.ts
Closing out our second zepbound price toggle test.
Learnings [here](https://www.notion.so/photons/GLP-1-Pricing-Zepbound-1bc8bfbbf4ec80f498f3e96c231a99d2?pvs=4).
> disable zepbound test

- packages/elements/package.json
https://www.notion.so/photons/Collapse-prescriber-form-after-a-template-edit-1cb8bfbbf4ec80aab2c9c4da030a328d?pvs=4
> Bump elements - release Edit UX improvement

- apps/patient/src/views/Pharmacy.tsx
we're going to have more than one org using this feature soon so want to bea ble to track and sumamrize actions by org id
> adding org id to tracking rum action

- apps/patient/src/views/Pharmacy.tsx
> adding measured to make an offers request; enabling it in amazon pharmacy pilot

- .gitignore
- apps/patient/src/views/Pharmacy.tsx
- packages/settings/src/lib/neutron.ts
- packages/settings/src/lib/photon.ts
This reverts commit da843b38f493141a50e32d38ff5aa55707e99327.
> Rollback photon

- .gitignore
- apps/patient/src/views/Pharmacy.tsx
- packages/settings/src/lib/neutron.ts
- packages/settings/src/lib/photon.ts
Reverts Photon-Health/client#1736
> Revert "Rollback photon"
